'use strict';
const crossingScene=new THREE.Scene();crossingScene.background=new THREE.Color(0x010208);
const crossingRoot=new THREE.Group();crossingScene.add(crossingRoot);
const crossingUniforms={time:{value:0}};
let crossingTime=0,wakeTime=0;
const holeRoot=new THREE.Group();crossingRoot.add(holeRoot);
const eventHorizon=new THREE.Mesh(new THREE.SphereGeometry(22,64,40),new THREE.MeshBasicMaterial({color:0x000000}));holeRoot.add(eventHorizon);
const diskMaterial=new THREE.ShaderMaterial({side:THREE.DoubleSide,transparent:true,depthWrite:false,uniforms:crossingUniforms,vertexShader:'varying vec3 vDisk;void main(){vDisk=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`uniform float time;varying vec3 vDisk;${noiseGLSL}
void main(){float r=length(vDisk.xy);float a=atan(vDisk.y,vDisk.x);float swirl=noise(vec3(cos(a+time*.5+r*.025)*9.,sin(a+time*.5+r*.025)*9.,r*.15));float streak=pow(.5+.5*sin(a*48.+r*.6-time*5.),4.);float heat=pow(clamp(1.-(r-24.)/76.,0.,1.),1.5);vec3 color=mix(vec3(.7,.055,.008),vec3(3.2,1.5,.4),heat);color+=vec3(.5,.6,1.)*streak*.25;float edge=smoothstep(24.,29.,r)*(1.-smoothstep(80.,105.,r));gl_FragColor=vec4(color*(.55+swirl+streak*.3),edge*.95);}`});
const accretionDisk=new THREE.Mesh(new THREE.RingGeometry(24,105,192,10),diskMaterial);accretionDisk.rotation.x=1.04;accretionDisk.rotation.y=.12;holeRoot.add(accretionDisk);
// The upper arc suggests the far side of the disk bent around the event horizon.
const lensedArc=new THREE.Mesh(new THREE.TorusGeometry(28,1.4,12,128),new THREE.MeshBasicMaterial({color:0xffc67a}));holeRoot.add(lensedArc);
const photonRing=new THREE.Mesh(new THREE.TorusGeometry(22.5,.25,8,128),new THREE.MeshBasicMaterial({color:0xfff0bf}));holeRoot.add(photonRing);
const holeGlow=glow(holeRoot,0xff9f4b,170,new V(0,0,-5),.45);holeGlow.material.depthTest=true;
const tunnelMaterial=new THREE.ShaderMaterial({side:THREE.BackSide,uniforms:crossingUniforms,vertexShader:'varying vec2 vTube;uniform float time;void main(){vTube=uv;vec3 p=position;p.x+=sin(p.y*.015+time)*6.;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}',fragmentShader:`varying vec2 vTube;uniform float time;${noiseGLSL}
void main(){float lanes=pow(.5+.5*sin(vTube.x*180.+sin(vTube.y*12.-time)*2.),18.);float rings=pow(.5+.5*sin(vTube.y*140.-time*16.),12.);float cloud=noise(vec3(vTube.x*30.,vTube.y*28.-time*2.,time*.1));vec3 c=mix(vec3(.008,.025,.09),vec3(.32,.07,.7),cloud);c+=vec3(.18,.9,1.8)*lanes*.9+vec3(.45,.4,.9)*rings*.6;gl_FragColor=vec4(c,1.);}`});
const crossingTunnel=new THREE.Mesh(new THREE.CylinderGeometry(48,48,1800,80,80,true),tunnelMaterial);crossingTunnel.rotation.x=Math.PI/2;crossingTunnel.position.z=-650;crossingTunnel.visible=false;crossingRoot.add(crossingTunnel);
const trailArray=new Float32Array(300*6),trailSeeds=[];for(let i=0;i<300;i++){const a=rand()*Math.PI*2,r=35+rand()*130;trailSeeds.push({x:Math.cos(a)*r,y:Math.sin(a)*r,z:rand()*650});}
const trailGeo=new THREE.BufferGeometry();trailGeo.setAttribute('position',new THREE.BufferAttribute(trailArray,3));const crossingTrails=new THREE.LineSegments(trailGeo,new THREE.LineBasicMaterial({color:0x9ce9ff,transparent:true,opacity:.65,blending:THREE.AdditiveBlending}));crossingRoot.add(crossingTrails);
const transitShip=shipModel.clone(true);transitShip.scale.setScalar(1.3);crossingRoot.add(transitShip);crossingScene.add(new THREE.HemisphereLight(0xb0d9ff,0x422111,2));
const backgroundStars=[];for(let i=0;i<2200;i++){const v=new V(rand()-.5,rand()-.5,rand()-.5).normalize().multiplyScalar(600+rand()*500);backgroundStars.push(...v.toArray());}const crossingStars=new THREE.Points(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(backgroundStars,3)),new THREE.PointsMaterial({color:0xc5dcff,size:1.7}));crossingRoot.add(crossingStars);
function beginCrossing(){groundActive=false;mode='crossing';crossingTime=0;clearInput();releaseMouse();holeRoot.visible=true;crossingTunnel.visible=false;transitShip.visible=true;crossingStars.visible=true;camera.fov=65;camera.updateProjectionMatrix();$('crossing').classList.remove('hidden');$('crossingDestination').textContent='DESTINATION / '+Campaign.universes[save.universe].name.toUpperCase();$('crossingCaption').textContent='The guardian is gone. The event horizon is pulling us in.';$('crossingFlash').style.opacity='0';}
function finishCrossing(){if(mode!=='crossing')return;$('crossing').classList.add('hidden');$('crossingFlash').style.opacity='0';selectUniverse();enterBase();beginWake();}
function beginWake(){groundActive=true;mode='waking';wakeTime=0;clearInput();releaseMouse();walker.set(-11,2,142);groundYaw=-Math.PI/2;groundPitch=0;camera.fov=70;camera.updateProjectionMatrix();$('wake').classList.remove('hidden');$('wakeStation').textContent=`ARK ${save.universe+1} / MEDICAL RECOVERY`;$('wakeLine').textContent='Dr. Imani: “Easy. You made it through. You are safe aboard the station.”';$('wakeRise').disabled=true;updateWakeCamera(0);}
function updateWakeCamera(t){const rise=THREE.MathUtils.smoothstep(t,3,7);camera.position.set(THREE.MathUtils.lerp(-17,-11,rise),THREE.MathUtils.lerp(1.7,1.97,rise),142);camera.rotation.set(THREE.MathUtils.lerp(1.15,0,rise),-Math.PI/2,THREE.MathUtils.lerp(-.12,0,rise),'YXZ');const blink=t<1?1:t<2?1-(t-1):t<2.4?(t-2)*1.8:t<3?Math.max(0,.72-(t-2.4)*1.2):0;$('wake').style.setProperty('--blink',blink);$('scene').style.filter=`blur(${Math.max(0,5-t)}px)`;}
function finishWake(){if(mode!=='waking'||wakeTime<2)return;$('wake').classList.add('hidden');$('scene').style.filter='';save.pendingWake=false;mode='walking';walker.set(-11,2,142);groundYaw=-Math.PI/2;groundPitch=0;updateGroundCamera();clearInput();persist();toast('Recovered at medical · E to talk with the crew · Follow the corridor to your ship.');}
function crossingTick(dt){if(mode==='waking'){wakeTime+=dt;updateWakeCamera(wakeTime);$('wakeRise').disabled=wakeTime<2;if(wakeTime>=8)finishWake();return;}if(mode!=='crossing')return;crossingTime+=dt;const t=crossingTime;crossingUniforms.time.value=t;accretionDisk.rotation.z=t*.35;photonRing.rotation.z=t*.3;const inside=t>=7.5;holeRoot.visible=!inside;crossingTunnel.visible=inside;transitShip.visible=t<6.8;crossingStars.visible=!inside;
 if(!inside){const approach=THREE.MathUtils.smoothstep(t,0,7.5);camera.position.set(Math.sin(t*.6)*8*(1-approach),8*(1-approach),240*(1-approach)+2);camera.lookAt(0,0,-10);camera.rotateZ(Math.sin(t*.5)*.1+Math.max(0,t-5)*.17);transitShip.position.set(Math.sin(t*.7)*4,-5,180*(1-approach)-18);transitShip.rotation.z=Math.sin(t)*.15;camera.fov=65+approach*35;$('crossingCaption').textContent=t<4?'The guardian is gone. The event horizon is pulling us in.':'HULL STRESS RISING / HOLD ON';}else{camera.position.set(Math.sin(t)*3,Math.cos(t*.8)*3,-(t-7.5)*180);camera.rotation.set(0,0,(t-7.5)*.65);camera.fov=105;$('crossingCaption').textContent=t<10?'BEYOND THE HORIZON / NO SIGNAL':'ARK RECOVERY BEACON ACQUIRED';}camera.updateProjectionMatrix();
 for(let i=0;i<trailSeeds.length;i++){const s=trailSeeds[i],z=camera.position.z-((s.z-t*(inside?420:80))%650+650)%650;const at=i*6;trailArray[at]=s.x;trailArray[at+1]=s.y;trailArray[at+2]=z;trailArray[at+3]=s.x;trailArray[at+4]=s.y;trailArray[at+5]=z+(inside?80:8+t*2);}trailGeo.attributes.position.needsUpdate=true;
 $('crossingFlash').style.opacity=t<10.7?'0':String(Math.min(1,(t-10.7)/1.3));if(t>=12)finishCrossing();}
$('skipCrossing').onclick=finishCrossing;$('wakeRise').onclick=finishWake;
selectUniverse();stationWorld();groundActive=true;updateGroundCamera();mode='welcome';if(save.introSeen)$('start').innerHTML='Return to base <span>↗</span>';requestAnimationFrame(frame);
