'use strict';
let mapReturn='playing',pauseReturn='playing',groundKind='station',groundPlanet=null,groundActive=true,groundYaw=0,groundPitch=0,walkVelocity=0,walkJump=0,walkTime=0,transition=null;
const walker=new V(0,2,20),groundScene=new THREE.Scene(),groundRoot=new THREE.Group();groundScene.add(groundRoot);
const groundAmbient=new THREE.HemisphereLight(0xb2dfff,0x26333b,2.2);groundScene.add(groundAmbient);
const groundSun=new THREE.DirectionalLight(0xffe3be,3.2);groundSun.position.set(-80,130,40);groundScene.add(groundSun);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;groundSun.castShadow=true;groundSun.shadow.mapSize.set(2048,2048);Object.assign(groundSun.shadow.camera,{left:-120,right:120,top:120,bottom:-120,near:1,far:450});groundSun.shadow.bias=-.0004;groundSun.shadow.normalBias=.04;
function terrainMaterial(p){const material=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.92,metalness:.03});material.onBeforeCompile=shader=>{shader.vertexShader='varying vec3 vSurvey;\n'+shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvSurvey=position;');shader.fragmentShader='varying vec3 vSurvey;\n'+noiseGLSL+'\n'+shader.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
float grain=noise(vSurvey*2.6);float strata=noise(vSurvey*.23);float grit=noise(vSurvey*18.);diffuseColor.rgb*=.52+grain*.65+strata*.28+grit*.15;
${p.id%6===2?'float vein=1.-smoothstep(.012,.045,abs(noise(vSurvey*.09)-.48));diffuseColor.rgb=mix(diffuseColor.rgb,vec3(2.,.22,.015),vein*.85);':''}`);};return material;}

let parkedShip=null,groundPickups=[],groundObstacles=[],groundDecor=[],groundTerrain=null;
const stationPoint={id:-1,name:'ARK / HOME STATION',pos:new V(),radius:70};
const stationExterior=new THREE.Group();scene.add(stationExterior);
const expGeo={box:new THREE.BoxGeometry(1,1,1),rock:new THREE.IcosahedronGeometry(1,1),crystal:new THREE.OctahedronGeometry(1),sphere:new THREE.SphereGeometry(1,20,12),cylinder:new THREE.CylinderGeometry(1,1,1,16),cone:new THREE.ConeGeometry(1,1,12)};
function detail(shape,color,parent,pos,scale,emission=0){const m=makeMesh(expGeo[shape],color,parent,new V(...pos),emission);m.scale.set(...scale);m.material.roughness=.6;m.castShadow=emission===0;m.receiveShadow=true;return m;}
function sign(text,parent,pos,width=12,color='#9deaff') {const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle=color;ctx.font='600 52px monospace';ctx.textAlign='center';ctx.fillText(text,512,80);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const obj=new THREE.Mesh(new THREE.PlaneGeometry(width,width/8),new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false,side:THREE.DoubleSide}));obj.position.set(...pos);parent.add(obj);return obj;}
// The orbital base remains a real destination during free flight.
for(const side of [-1,1]){detail('box',0x374a62,stationExterior,[side*45,0,5],[24,32,105]);for(let j=0;j<5;j++){detail('box',0x74dfff,stationExterior,[side*32,4,j*16-28],[1,3,6],2);detail('box',0x132135,stationExterior,[side*65,0,j*18-30],[32,1,13]);}}
detail('box',0x2d425b,stationExterior,[0,-18,0],[110,5,110]);detail('box',0x425a74,stationExterior,[0,19,18],[110,4,76]);const stationRing=makeMesh(new THREE.TorusGeometry(95,4,12,100),0x5e8ca3,stationExterior);stationRing.rotation.y=Math.PI/2;const stationBeacon=glow(stationExterior,0x7feaff,65,new V(0,0,-45));
sign('ARK / DOCK 01',stationExterior,[0,17,-55],50);
function groundVisible(){return groundActive;}
function clearGround(){groundRoot.traverse(o=>{if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){if(m.map&&m.map!==glowMap)m.map.dispose();m.dispose();}}if(o.geometry&&!Object.values(expGeo).includes(o.geometry)&&!o.userData.sharedGeometry)o.geometry.dispose();});groundRoot.clear();stationCrew=[];groundPickups=[];groundObstacles=[];groundDecor=[];groundTerrain=null;}
function parkedKestrel(pos){const root=new THREE.Group();groundRoot.add(root);root.position.copy(pos);const model=shipModel.clone(true);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}if(o.material)o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();o.userData.sharedGeometry=true;});root.add(model);for(const x of [-2.8,2.8]){detail('cylinder',0x8cabbf,root,[x,-.5,1],[.12,1.3,.12]);detail('box',0x253d53,root,[x,-1.1,1],[1,.18,1.2]);}return root;}
function stationWorld(){hp=maxHp();novaCooldown=0;clearGround();groundKind='station';groundPlanet=null;groundScene.background=new THREE.Color(0x020815);groundScene.fog=new THREE.FogExp2(0x020815,.004);groundAmbient.color.setHex(0xaacfff);groundAmbient.intensity=2.4;groundSun.intensity=3;
 detail('box',0x15273c,groundRoot,[0,-.65,-9],[48,1.3,94]);
 for(let x=-20;x<=20;x+=4)for(let z=-48;z<=32;z+=4){const tile=detail('box',(x/4+z/4)%2?0x21374b:0x1c2f43,groundRoot,[x,0,z],[3.94,.12,3.94]);tile.material.metalness=.25;tile.material.roughness=.45;}
 for(const x of [-23,23]){detail('box',0x0c192e,groundRoot,[x,9,-10],[2,18,92]);for(let z=-45;z<32;z+=12){detail('box',0x435d78,groundRoot,[x*.96,7,z],[1.4,14,1.3]);detail('box',0x8cddff,groundRoot,[x*.93,11,z],[.25,7,.3],2);detail('box',0x395773,groundRoot,[x*.92,3,z+4],[.4,3,5]);}}
 for(let z=-36;z<36;z+=12){detail('box',0x253d55,groundRoot,[0,17,z],[46,1,1]);detail('box',0xbbefff,groundRoot,[0,16.3,z],[18,.12,.5],2);}
 for(const x of [-7,7])for(let z=-42;z<28;z+=3)detail('box',Campaign.universes[save.universe].color,groundRoot,[x,.13,z],[.1,.08,1.7],2);
 for(let z=-4;z<26;z+=6){const arrow=detail('cone',0x9effef,groundRoot,[0,.16,z],[.65,1.2,.04],1);arrow.rotation.x=-Math.PI/2;}
 detail('box',0x83dcff,groundRoot,[0,9,-53],[44,18,.15],.15).material.setValues({transparent:true,opacity:.12,depthWrite:false});
 sign('ARK / '+String(save.universe+1).padStart(2,'0'),groundRoot,[0,12,-51],25);sign('KESTREL / BOARDING',groundRoot,[0,5,-22],13);
 for(const side of [-1,1]){const desk=detail('box',0x213e58,groundRoot,[side*15,1.1,12],[5,2.2,3]);groundObstacles.push({x:side*15,z:12,r:3.2});const monitor=detail('box',0x2eebdf,groundRoot,[side*15,2.5,11.6],[4,1.4,.15],1);monitor.rotation.x=-.3;sign(side<0?'NAVIGATION':'SYSTEMS ONLINE',groundRoot,[side*15,4.5,11.5],8);}
 for(let i=0;i<16;i++){const x=(i%2?1:-1)*(13+(i%3)*2),z=-32+Math.floor(i/2)*5;detail('box',0x3a4c62,groundRoot,[x,1,z],[2,2,2]);groundObstacles.push({x,z,r:1.8});detail('box',0xffbd76,groundRoot,[x,1.7,z-1.02],[1.2,.12,.04],1);}
 const viewPlanet=makeMesh(new THREE.SphereGeometry(40,48,32),Campaign.universes[save.universe].color,groundRoot,new V(-30,25,-190));viewPlanet.material.roughness=.8;const rim=makeMesh(new THREE.TorusGeometry(65,1,8,100),0xbacaff,groundRoot,new V(-30,25,-190),.5);rim.rotation.x=1.1;
 const starData=[];for(let i=0;i<1000;i++)starData.push((rand()-.5)*800,rand()*250-60,-250-rand()*400);const starMesh=new THREE.Points(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(starData,3)),new THREE.PointsMaterial({color:0xb8dbff,size:1.4}));groundRoot.add(starMesh);
 buildStationModules();parkedShip=parkedKestrel(new V(0,1.3,-14));walker.set(0,2,21);groundYaw=groundPitch=0;walkJump=walkVelocity=0;
}
function heightAt(x,z){if(groundKind==='station')return .12;const k=(groundPlanet.id+1)*.27;const edge=Math.min(1,Math.max(0,(Math.hypot(x,z)-18)/35));return edge*(Math.sin(x*.031+k)*Math.cos(z*.037)*7+Math.sin((x+z)*.08+k)*2);}
function surfaceWorld(p){const previousSeed=seed;seed=(p.id+1)*7919;clearGround();groundKind='surface';groundPlanet=p;const color=p.biome.color;groundScene.background=new THREE.Color(p.biome.fog).lerp(new THREE.Color(color),.28);groundScene.fog=new THREE.FogExp2(groundScene.background,.0023);groundAmbient.color.setHex(color);groundAmbient.intensity=2.3;groundSun.color.setHex(p.id%6===2?0xffbd83:0xffecd2);groundSun.intensity=3;
 const geo=new THREE.PlaneGeometry(640,640,128,128);geo.rotateX(-Math.PI/2);const positions=geo.attributes.position;const colors=[];for(let i=0;i<positions.count;i++){const x=positions.getX(i),z=positions.getZ(i),h=heightAt(x,z);positions.setY(i,h);const c=new THREE.Color(p.biome.ground).lerp(new THREE.Color(color),.18+Math.max(0,h)*.035+rand()*.1);colors.push(c.r,c.g,c.b);}geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals();groundTerrain=new THREE.Mesh(geo,terrainMaterial(p));groundTerrain.receiveShadow=true;groundRoot.add(groundTerrain);
 // Instanced stones, vegetation and crystals keep the richly dressed surface inexpensive.
 const rockMat=new THREE.MeshStandardMaterial({color:p.id%6===1?0xb2d4ee:0x746b79,roughness:.9});const rockField=new THREE.InstancedMesh(expGeo.rock,rockMat,280);const transform=new THREE.Object3D();
 for(let i=0;i<280;i++){const a=rand()*Math.PI*2,r=35+rand()*260;let x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.abs(x)<38&&z<5&&z>-110)x+=(x<0?-1:1)*55;transform.position.set(x,heightAt(x,z)+1,z);transform.rotation.set(rand()*3,rand()*6,rand()*3);const size=1+rand()*6;transform.scale.set(size,size*(.4+rand()),size);transform.updateMatrix();rockField.setMatrixAt(i,transform.matrix);if(r<220)groundObstacles.push({x,z,r:size*.65});}rockField.castShadow=true;rockField.receiveShadow=true;groundRoot.add(rockField);
 const plantShape=p.id%6===0||p.id%6===5?'cone':'crystal';const plantMat=new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:p.id%6===2?.5:.12,roughness:.6});const plants=new THREE.InstancedMesh(expGeo[plantShape],plantMat,220);
 for(let i=0;i<220;i++){const a=rand()*Math.PI*2,r=28+rand()*240;const x=Math.cos(a)*r,z=Math.sin(a)*r;const h=3+rand()*12;transform.position.set(x,heightAt(x,z)+h*.4,z);transform.rotation.set(0,rand()*6,plantShape==='crystal'?(rand()-.5)*.5:0);transform.scale.set(1+rand()*3,h,1+rand()*3);transform.updateMatrix();plants.setMatrixAt(i,transform.matrix);}plants.castShadow=true;plants.receiveShadow=true;groundRoot.add(plants);
 if(plantShape==='cone'){const trunks=new THREE.InstancedMesh(expGeo.cylinder,new THREE.MeshStandardMaterial({color:p.id%6===0?0x435c46:0x417c80,roughness:1}),220);const matrix=new THREE.Matrix4();for(let i=0;i<220;i++){plants.getMatrixAt(i,matrix);matrix.decompose(transform.position,transform.quaternion,transform.scale);transform.scale.x*=.22;transform.scale.z*=.22;transform.position.y-=transform.scale.y*.25;transform.updateMatrix();trunks.setMatrixAt(i,transform.matrix);}trunks.castShadow=true;groundRoot.add(trunks);}
 const mountains=new THREE.InstancedMesh(expGeo.rock,new THREE.MeshStandardMaterial({color:new THREE.Color(p.biome.ground).lerp(new THREE.Color(0x78849a),.35),roughness:1}),36);for(let i=0;i<36;i++){const a=i*Math.PI*2/36;transform.position.set(Math.cos(a)*370,10,Math.sin(a)*370);transform.rotation.set(rand()*.3,rand()*6,rand()*.3);transform.scale.set(35+rand()*30,25+rand()*65,35+rand()*20);transform.updateMatrix();mountains.setMatrixAt(i,transform.matrix);}groundRoot.add(mountains);
 // A recoverable alien ruin is the visual destination of each expedition.
 for(const x of [-12,12]){const z=-82;detail('box',0x66798c,groundRoot,[x,heightAt(x,z)+10,z],[4,20,4]);detail('box',color,groundRoot,[x,heightAt(x,z)+10,z+2.1],[.25,15,.1],2);}detail('box',0x718395,groundRoot,[0,heightAt(0,-82)+20,-82],[30,3,5]);sign('ANCIENT SIGNAL',groundRoot,[0,heightAt(0,-79)+12,-79],18);
 const moon=makeMesh(new THREE.SphereGeometry(65,48,32),new THREE.Color(color).lerp(new THREE.Color(0xffffff),.5),groundRoot,new V(190,125,-330));moon.material.dispose();moon.material=new THREE.ShaderMaterial({vertexShader:planetVertex,fragmentShader:planetFragment,uniforms:{kind:{value:(p.id+3)%6},variant:{value:p.id*2.31},tint:{value:new THREE.Color(color)}}});const ring=makeMesh(new THREE.TorusGeometry(95,.7,8,100),color,groundRoot,new V(190,125,-330),.8);ring.rotation.x=1.1;
 const sunOrb=makeMesh(expGeo.sphere,0xffe0b0,groundRoot,new V(-220,190,-390),3);sunOrb.scale.setScalar(25);glow(groundRoot,0xffd2a3,140,sunOrb.position,.6);
 const dustPositions=[];for(let i=0;i<300;i++)dustPositions.push((rand()-.5)*440,rand()*40,(rand()-.5)*440);const motes=new THREE.Points(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(dustPositions,3)),new THREE.PointsMaterial({size:.2,color,transparent:true,opacity:.65}));groundRoot.add(motes);groundDecor.push(motes);
 parkedShip=parkedKestrel(new V(0,1.4,8));detail('cylinder',0x2a3e52,groundRoot,[0,.04,8],[9,.12,9]);
 const locations=[[8,-13],[-17,-23],[23,-37],[-26,-51],[15,-61],[-7,-74],[30,-87],[0,-83]];
 locations.forEach(([x,z],slot)=>{const type=slot===7?'relic':slot%2?'crystal':'alloy';if(save.collected.includes(`${p.id}:${slot}`))return;const root=new THREE.Group();root.position.set(x,heightAt(x,z)+1.1,z);groundRoot.add(root);const item=detail(type==='alloy'?'box':type==='relic'?'sphere':'crystal',type==='relic'?0xffd686:type==='crystal'?0x7ceeff:0xb2c8da,root,[0,0,0],type==='alloy'?[1,.6,.8]:[.6,1.2,.6],1);glow(root,type==='relic'?0xffd686:0x74eaff,4,new V(),.6);groundPickups.push({root,item,type,slot,baseY:root.position.y});});
 walker.set(0,2,0);groundYaw=groundPitch=0;walkJump=walkVelocity=0;seed=previousSeed;
}
function selectUniverse(){planets=allPlanets.filter(p=>p.universe===save.universe);for(const p of allPlanets)p.group.visible=p.universe===save.universe;stationPoint.name=`ARK ${save.universe+1} / HOME STATION`;stationBeacon.material.color.setHex(Campaign.universes[save.universe].color);sky.rotation.y=save.universe*.9;sun.material.color.setHex(Campaign.universes[save.universe].color);resetFlight();}
function enterBase(){resetFlight();groundActive=true;stationWorld();mode='walking';clearInput();camera.fov=70;camera.updateProjectionMatrix();updateGroundCamera();persist();}
function showBriefing(){mode='briefing';releaseMouse();$('briefingChapter').textContent=`CHAPTER ${save.universe+1} / ${Campaign.universes[save.universe].chapter.toUpperCase()}`;$('briefingTitle').textContent=save.universe===0?'Six universes. One way home.':Campaign.universes[save.universe].name;const lines=['The gates went dark. Twenty-four worlds in each of six universes were cut off from their stations. You are the pilot of the Kestrel, the last ship able to follow the signal.','The first gate has carried you into a frozen universe. Beneath its glass oceans, old transmitters still call for help.','Your instruments detect the same signal inside the stars. Someone built this prison, and the next guardian knows why.','The station remembers you before you arrive. The signal is not just a weapon. It is a memory of the people stranded here.','Only two gates remain. The worlds beyond this station hold fragments of the original navigation key.','You have reached the source. Free the last twenty-four worlds and confront the Null Sovereign. Reconnect the six universes and bring everyone home.'];$('briefingText').textContent=lines[save.universe];$('briefing').classList.remove('hidden');}
function clearInput(){for(const k in keys)keys[k]=false;firing=false;steer.set(0,0);mouseMotion.set(0,0);turnRate.set(0,0);}
function updateGroundCamera(){camera.position.copy(walker);camera.position.y=heightAt(walker.x,walker.z)+1.85+walkJump+Math.sin(walkTime*9)*.035;camera.rotation.set(groundPitch,groundYaw,0,'YXZ');}
function groundLook(e){if(document.pointerLockElement===renderer.domElement){groundYaw-=e.movementX*.002;groundPitch=THREE.MathUtils.clamp(groundPitch-e.movementY*.002,-1.25,1.25);}}
function groundStep(dt){groundYaw+=((keys.ArrowLeft?1:0)-(keys.ArrowRight?1:0))*dt*1.6;groundPitch=THREE.MathUtils.clamp(groundPitch+((keys.ArrowUp?1:0)-(keys.ArrowDown?1:0))*dt,-1.25,1.25);const x=(keys.KeyD?1:0)-(keys.KeyA?1:0),z=(keys.KeyS?1:0)-(keys.KeyW?1:0);const movement=new V(x,0,z);if(movement.lengthSq()){movement.normalize().applyAxisAngle(upAxis,groundYaw).multiplyScalar(dt*(keys.ShiftLeft||keys.ShiftRight?10:5.5));const next=walker.clone().add(movement);if(groundKind==='station')constrainStationStep(next,walker);else{next.x=THREE.MathUtils.clamp(next.x,-225,225);next.z=THREE.MathUtils.clamp(next.z,-225,225);}for(const obstacle of groundObstacles){const dx=next.x-obstacle.x,dz=next.z-obstacle.z,d=Math.hypot(dx,dz);if(d<obstacle.r+.6&&d>.001){next.x=obstacle.x+dx/d*(obstacle.r+.6);next.z=obstacle.z+dz/d*(obstacle.r+.6);}}if(groundKind==='station')constrainStationStep(next,walker);walker.copy(next);walkTime+=dt;}if(keys.Space&&walkJump===0)walkVelocity=5;if(walkVelocity!==0||walkJump>0){walkVelocity-=12*dt;walkJump=Math.max(0,walkJump+walkVelocity*dt);if(walkJump===0)walkVelocity=0;}updateGroundCamera();}
function nearestPickup(){return groundPickups.filter(p=>p.root.position.distanceTo(walker)<4).sort((a,b)=>a.root.position.distanceToSquared(walker)-b.root.position.distanceToSquared(walker))[0];}
function groundInteract(){if(mode!=='walking')return;const crew=closestCrew();if(crew){talkToCrew(crew);return;}const pickup=nearestPickup();if(pickup){if(Campaign.collect(save,groundPlanet.id,pickup.slot,pickup.type)){groundRoot.remove(pickup.root);disposeObject(pickup.root);groundPickups.splice(groundPickups.indexOf(pickup),1);persist();toast(`${pickup.type.toUpperCase()} recovered · +${pickup.type==='relic'?90:pickup.type==='crystal'?35:20} crystals`);}return;}if(parkedShip.position.distanceTo(walker)<9){beginLaunch();return;}toast('Approach a crew member, the Kestrel, or a glowing item, then press E.');}
function beginLaunch(){clearInput();mode='launch';transition={time:0,type:'launch',from:camera.position.clone(),shipFrom:parkedShip.position.clone()};releaseMouse();$('travelLabel').textContent=groundKind==='station'?'DEPARTING ARK / AIRLOCK OPEN':'ASCENT / RETURNING TO ORBIT';$('travel').classList.remove('hidden');}
function finishLaunch(){groundActive=false;mode='playing';if(groundKind==='station'){ship.position.set(0,0,-210);ship.quaternion.identity();current=null;}else{ship.position.copy(groundPlanet.pos).add(new V(0,0,groundPlanet.radius+420));ship.quaternion.identity();current=groundPlanet;target=groundPlanet;selected=target.id;}forward.copy(forwardAxis).applyQuaternion(ship.quaternion);right.copy(rightAxis).applyQuaternion(ship.quaternion);up.copy(upAxis).applyQuaternion(ship.quaternion);camera.position.copy(ship.position).addScaledVector(forward,-22).addScaledVector(up,6);camera.quaternion.copy(ship.quaternion);speed=0;autoPilot=false;invulnerable=3;clearInput();$('travel').classList.add('hidden');transition=null;persist();toast('W forward · S reverse · B brake · M map · H base · L land');}
function baseCourse(){if(mode!=='playing')return;if(finalActive){toast('Defeat the guardian before returning to base.');return;}target=stationPoint;selected=planets[0].id;autoPilot=false;toast('Base course set · F autopilot · L to dock within 650 m');}
function tryLanding(){if(mode!=='playing'||finalActive)return;const baseNearby=ship.position.distanceTo(stationPoint.pos)<650;const p=current;const planetNearby=p&&ship.position.distanceTo(p.pos)<p.radius+650;if(!baseNearby&&(!planetNearby||!getEncounter(p).cleared)){toast(planetNearby?'Landing blocked · Defeat every orbital fleet first.':'Approach a secured planet or the base to land.');return;}if(enemies.length){toast('Landing blocked · Clear the hostile fleet first.');return;}if(Math.abs(speed)>120){toast('Hold B to slow below 120 m/s before landing.');return;}clearInput();autoPilot=false;speed=0;mode='landing';transition={type:'landing',time:0,planet:baseNearby?null:p,from:ship.position.clone()};releaseMouse();$('travelLabel').textContent=baseNearby?'DOCKING / WELCOME HOME':'DESCENT / '+p.name.toUpperCase();$('travel').classList.remove('hidden');}
function expeditionTick(dt){stationLifeTick(dt);crossingTick(dt);stationRing.rotation.x+=dt*.045;if(mode==='walking')groundStep(dt);for(const p of groundPickups){p.item.rotation.y+=dt;p.root.position.y=p.baseY+Math.sin(elapsed*2+p.slot)*.18;}for(const o of groundDecor)o.rotation.y+=dt*.005;if(groundActive){elapsed+=dt;groundSun.position.set(walker.x-80,130,walker.z+40);groundSun.target.position.set(walker.x,0,walker.z);groundSun.target.updateMatrixWorld();}
 if(mode==='launch'&&transition){transition.time+=dt;const t=transition.time;parkedShip.position.copy(transition.shipFrom).add(new V(0,groundKind==='station'?Math.min(2,t):t*t*1.4,-(Math.max(0,t-1)**2)*8));const view=parkedShip.position.clone().add(new V(0,4,17));camera.position.lerp(view,.08);camera.lookAt(parkedShip.position);if(t>4.5)finishLaunch();}
 if(mode==='landing'&&transition){transition.time+=dt;const t=Math.min(1,transition.time/3);const destination=transition.planet?transition.planet.pos.clone().add(new V(0,0,transition.planet.radius+22)):new V(0,0,-60);ship.position.lerpVectors(transition.from,destination,t*t*(3-2*t));camera.position.copy(ship.position).add(new V(12,10,25));camera.lookAt(ship.position);if(t>=1){groundActive=true;if(transition.planet)surfaceWorld(transition.planet);else stationWorld();transition=null;mode='walking';$('travel').classList.add('hidden');clearInput();updateGroundCamera();persist();}}
}
function expeditionHud(){document.body.classList.toggle('in-crossing',['crossing','waking'].includes(mode));document.body.classList.toggle('on-foot',groundActive);$('universeLabel').textContent=`${String(save.universe+1).padStart(2,'0')} / ${Campaign.universes[save.universe].name.toUpperCase()}`;$('inventory').textContent=`ALLOY ${save.inventory.alloy}  ·  CRYSTAL ${save.inventory.crystal}  ·  RELIC ${save.inventory.relic}`;$('credits').textContent='◈ '+save.credits;$('cleared').textContent=String(securedWorldCount()).padStart(2,'0');$('footHint').classList.toggle('hidden',!groundActive||!['walking','paused','map'].includes(mode));$('landButton').classList.toggle('hidden',groundActive);if(!groundActive){$('stationDirectory').classList.add('hidden');$('landButton').disabled=mode!=='playing';return;}const pickup=nearestPickup(),nearShip=parkedShip&&parkedShip.position.distanceTo(walker)<9;let hint=pickup?`E · Collect ${pickup.type}`:nearShip?'E · Board Kestrel and launch':groundKind==='station'?'Explore the crew modules behind the hangar · E to talk':'Explore glowing artifacts · Return to your ship to launch';if(groundKind==='surface'&&!pickup&&!nearShip){const closest=groundPickups.slice().sort((a,b)=>a.root.position.distanceToSquared(walker)-b.root.position.distanceToSquared(walker))[0];hint=closest?`${closest.type.toUpperCase()} · ${Math.round(closest.root.position.distanceTo(walker))} m · E to collect nearby`:'Landing site surveyed · Return to the Kestrel';}$('footAction').textContent=hint;$('footLocation').textContent=groundKind==='station'?`ARK ${save.universe+1} / HANGAR DECK`:`${groundPlanet.name.toUpperCase()} / SURFACE`;$('footShip').textContent=parkedShip?`SHIP ${Math.round(parkedShip.position.distanceTo(walker))} m`:'';$('interactButton').disabled=mode!=='walking';stationLifeHud();}
$('briefingContinue').onclick=()=>{$('briefing').classList.add('hidden');mode='walking';clearInput();captureMouse();};$('interactButton').onclick=groundInteract;$('landButton').onclick=tryLanding;$('baseButton').onclick=()=>{if(mode==='map'){closeMap();if(mode==='playing')baseCourse();else toast('Board your ship to plot a flight course.');}else baseCourse();};
$('craftRepair').onclick=()=>{if(save.inventory.alloy<3){toast('Collect 3 alloy on secured planets.');return;}save.inventory.alloy-=3;save.credits+=120;persist();renderMap();toast('Alloy traded · +120 upgrade credits');};
$('craftCore').onclick=()=>{if(save.inventory.crystal<3||save.inventory.relic<1){toast('Collect 3 crystals and 1 relic on secured planets.');return;}save.inventory.crystal-=3;save.inventory.relic--;save.credits+=350;persist();renderMap();toast('Artifact core traded · +350 upgrade credits');};
