/* STARFARER — a tiny, offline 3D exploration game. */
'use strict';
const $=id=>document.getElementById(id);
if(!window.THREE){$('overlay').innerHTML='<div class="dialog">The 3D library could not load. Keep the vendor folder beside index.html.</div>';throw Error('Missing THREE');}
const biomes=[
 {name:'Emerald Reach',color:0x57c68b,ground:0x123e34,fog:0x09272c,mob:'Spore swarm',type:'swarm'},
 {name:'Glacial Veil',color:0x8ddcf4,ground:0x294e68,fog:0x142b48,mob:'Frost sentinels',type:'shooter'},
 {name:'Ember Expanse',color:0xff8559,ground:0x512b2b,fog:0x301923,mob:'Magma brutes',type:'brute'},
 {name:'Amethyst Drift',color:0xb899ff,ground:0x392c60,fog:0x201b3c,mob:'Phase wisps',type:'wisp'},
 {name:'Golden Dunes',color:0xf0cf7b,ground:0x58482d,fog:0x322b21,mob:'Dune stalkers',type:'charger'},
 {name:'Tidal Frontier',color:0x56e6d7,ground:0x124d5a,fog:0x0a2b3c,mob:'Storm jellies',type:'jelly'}
];
const names=['Verdant Echo','Frosthaven','Cinder IX','Violet Moon','Solara','Pelagic Blue','Mosslight','Aurora Shelf','Ashen Crown','Prism Hollow','Dusthaven','Coral Night','Fernfall','Boreal Rift','Emberheart','Dreamglass','Saffron Sea','Deepwater','Canopy Prime','Winter Halo','Obsidian Sun','Amethyst Arc','Amber Reach','Pearl Abyss','Clover Vale','Icebound Eden','Molten Gate','Ghost Orchid','Ochre Moon','Siren Reef','Wildgrove','Snowblind','Flarepoint','Velvet Comet','Gilded Dusk','Azure Bloom','Jade Horizon','Polar Crown','Pyre World','Lilac Vortex','Sunken Gold','Opal Tide','Eden Beyond','Absolute Zero','Inferno Ultima','Astral Throne','Last Oasis','Ocean Eternal'];
const planets=names.map((name,i)=>({name,id:i,biome:biomes[i%6],tier:Math.floor(i/6)+1,boss:(i+1)%4===0}));
let save={credits:0,weapon:1,shield:1,cleared:[],last:0};
try{const s=JSON.parse(localStorage.getItem('starfarer-save-v1'));if(s&&Array.isArray(s.cleared))save={credits:Math.max(0,Number(s.credits)||0),weapon:Math.max(1,Math.min(8,Number(s.weapon)||1)),shield:Math.max(1,Math.min(8,Number(s.shield)||1)),cleared:s.cleared.filter(n=>Number.isInteger(n)&&n>=0&&n<48),last:Math.max(0,Math.min(47,Number(s.last)||0))};}catch{}
let storageWarned=false;function persist(){try{localStorage.setItem('starfarer-save-v1',JSON.stringify(save));}catch{if(!storageWarned){toast('Saving is unavailable in this browser. You can still play.');storageWarned=true;}}}
const scene=new THREE.Scene();scene.background=new THREE.Color(0x09272c);scene.fog=new THREE.FogExp2(0x09272c,.006);
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch(e){$('overlay').innerHTML='<div class="dialog"><h2>3D rendering is unavailable.</h2><p>Try Chrome with graphics acceleration enabled.</p></div>';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;$('scene').appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,650);camera.position.set(0,42,54);
scene.add(new THREE.HemisphereLight(0xd6faff,0x182022,2.3));const sun=new THREE.DirectionalLight(0xffe8c5,2.7);sun.position.set(30,70,20);scene.add(sun);
const world=new THREE.Group();scene.add(world);const terrain=new THREE.Group();world.add(terrain);
const ship=new THREE.Group();scene.add(ship);
function mesh(geometry,color,parent,x=0,y=0,z=0,emissive=false){const m=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color,roughness:.65,metalness:.18,emissive:emissive?color:0,emissiveIntensity:emissive?.7:0}));m.position.set(x,y,z);parent.add(m);return m;}
const hull=mesh(new THREE.ConeGeometry(.85,3.8,5),0xe4eee1,ship,0,0,-.2);hull.rotation.x=-Math.PI/2;
mesh(new THREE.BoxGeometry(3.8,.18,1.35),0x668d8d,ship,0,-.12,.65);mesh(new THREE.BoxGeometry(.7,.45,1.3),0x79f5e0,ship,0,.4,0,true);
for(const x of [-1.35,1.35]){mesh(new THREE.CylinderGeometry(.27,.36,1.6,8),0xc3dcd0,ship,x,0,.8).rotation.x=Math.PI/2;mesh(new THREE.ConeGeometry(.27,1.9,7),0x7affe5,ship,x,0,2.4,true).rotation.x=Math.PI/2;}
ship.position.y=3;
const ring=mesh(new THREE.TorusGeometry(2.6,.035,5,64),0x91f4d5,ship,0,-2.5,0,true);ring.rotation.x=Math.PI/2;
const starGeo=new THREE.BufferGeometry();const starPos=[];let seed=904;function random(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}
for(let i=0;i<1500;i++)starPos.push((random()-.5)*600,35+random()*220,(random()-.5)*600);starGeo.setAttribute('position',new THREE.Float32BufferAttribute(starPos,3));scene.add(new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xc4f8ef,size:.55,transparent:true,opacity:.85})));
const distant=mesh(new THREE.IcosahedronGeometry(24,3),0x4a9981,scene,65,50,-120);const orbit=mesh(new THREE.TorusGeometry(36,1,3,100),0xc4c09a,distant);orbit.rotation.x=1.1;orbit.rotation.y=.35;
let current=planets[save.last],selected=current.id,mode='welcome',hp=100,wave=0,totalWaves=3,kills=0,totalEnemies=0,spawnTimer=0,fireTimer=0,novaCooldown=0,invulnerable=0,elapsed=0,noticeTimer=0,started=false,clearedThisVisit=false;
const enemies=[],bullets=[],particles=[],drops=[];const keys={};let firing=false;const pointer=new THREE.Vector2(0,-.3),ray=new THREE.Raycaster(),aim=new THREE.Vector3(0,3,-20),plane=new THREE.Plane(new THREE.Vector3(0,1,0),-3);
const enemyShapes={swarm:new THREE.IcosahedronGeometry(1,0),shooter:new THREE.OctahedronGeometry(1.4),brute:new THREE.DodecahedronGeometry(1.8,0),wisp:new THREE.TorusKnotGeometry(.8,.24,28,5),charger:new THREE.ConeGeometry(1.2,2.6,4),jelly:new THREE.SphereGeometry(1.35,10,6)};
const bulletGeo=new THREE.SphereGeometry(.24,6,4),sparkGeo=new THREE.BoxGeometry(.22,.22,.22),crystalGeo=new THREE.OctahedronGeometry(.6);
function remove(obj,geometry=false){obj.traverse(m=>{if(m.isMesh||m.isLineSegments){if(geometry)m.geometry.dispose();if(Array.isArray(m.material))m.material.forEach(x=>x.dispose());else m.material.dispose();}});obj.removeFromParent();}
function resetObjects(list){for(const e of list)remove(e.obj);list.length=0;}
function createWorld(p){seed=1000+p.id*79;while(terrain.children.length)remove(terrain.children[0],true);scene.background.setHex(p.biome.fog);scene.fog.color.setHex(p.biome.fog);distant.material.color.setHex(p.biome.color);
 const floor=mesh(new THREE.CircleGeometry(110,80),p.biome.ground,terrain);floor.rotation.x=-Math.PI/2;floor.position.y=-1;
 const grid=new THREE.GridHelper(200,40,p.biome.color,p.biome.color);grid.material.transparent=true;grid.material.opacity=.055;grid.position.y=-.92;terrain.add(grid);
 for(let i=0;i<100;i++){const a=random()*Math.PI*2,r=12+Math.sqrt(random())*88,x=Math.cos(a)*r,z=Math.sin(a)*r,s=1+random()*3;
 const g=new THREE.Group();g.position.set(x,-.8,z);terrain.add(g);
 if(p.id%6===0){mesh(new THREE.CylinderGeometry(.25,.5,s*1.5,5),0x527067,g,0,s*.65,0);mesh(new THREE.ConeGeometry(s,s*2.7,6),p.biome.color,g,0,s*1.9,0);}
 else if(p.id%6===1||p.id%6===3){const c=mesh(new THREE.ConeGeometry(s*.6,s*3,5),p.biome.color,g,0,s,0);c.rotation.z=random()*.4;}
 else if(p.id%6===5){mesh(new THREE.SphereGeometry(s,8,5),p.biome.color,g,0,s*.4,0).scale.y=.4;for(let j=0;j<3;j++)mesh(new THREE.CylinderGeometry(.13,.2,s*2,5),0x80b8ba,g,j*.5,s*.6,0);}
 else {mesh(new THREE.DodecahedronGeometry(s,0),p.biome.color,g,0,s*.2,0).scale.y=p.id%6===2?1.4:.55;}
 }
 const boundary=mesh(new THREE.TorusGeometry(77,.12,4,128),p.biome.color,terrain,0,.1,0,true);boundary.rotation.x=Math.PI/2;
}
function toast(text){$('notice').textContent=text;$('notice').classList.add('show');noticeTimer=4;}
function maxHp(){return 100+(save.shield-1)*30;}
function hud(){ $('hpText').textContent=Math.ceil(hp/maxHp()*100)+'%';$('hpBar').style.width=Math.max(0,hp/maxHp()*100)+'%';$('hpBar').style.background=hp<maxHp()*.3?'#ff947e':'#bcffd1';$('credits').textContent='◈ '+save.credits;$('cleared').textContent=String(save.cleared.length).padStart(2,'0');$('upgradeText').textContent=`PLASMA MK ${save.weapon} · SHIELD MK ${save.shield}`;$('nova').textContent=novaCooldown>0?`NOVA RECHARGING / ${Math.ceil(novaCooldown)}s`:'NOVA READY / E';}
function beginPlanet(id){current=planets[id];selected=id;save.last=id;persist();resetObjects(enemies);resetObjects(bullets);resetObjects(particles);resetObjects(drops);createWorld(current);ship.position.set(0,3,15);hp=maxHp();wave=0;kills=0;totalEnemies=0;spawnTimer=2;fireTimer=0;novaCooldown=0;invulnerable=2;clearedThisVisit=false;mode='playing';started=true;totalWaves=current.tier>=5?4:3;
 ['overlay','map','pause'].forEach(id=>$(id).classList.add('hidden'));$('sector').textContent=`SECTOR ${String(current.id+1).padStart(2,'0')} / ${current.biome.name.toUpperCase()}`;$('planetName').textContent=current.name;$('mission').textContent=`${current.biome.name} · Threat level ${current.tier}${current.boss?' · Guardian detected':''}`;$('objective').textContent='Secure the landing zone';$('enemyInfo').textContent=current.biome.mob+' detected';$('wave').textContent='Incoming signals…';$('waveBar').style.width='0%';toast('Arrived at '+current.name+'. Fly with WASD. Hold Space to fire.');hud();}
function spawnWave(){wave++;let count=4+current.tier+wave;totalEnemies=count;kills=0;for(let i=0;i<count;i++){const boss=current.boss&&wave===totalWaves&&i===0;const type=current.biome.type;const obj=new THREE.Group();const body=mesh(enemyShapes[type],current.biome.color,obj,0,0,0,true);mesh(new THREE.SphereGeometry(.22,6,4),0xfff2d5,obj,0,.3,-1,true);if(type==='jelly')for(let j=0;j<4;j++)mesh(new THREE.CylinderGeometry(.08,.04,2,4),current.biome.color,obj,(j-1.5)*.5,-1.4,0,true);if(boss)obj.scale.setScalar(2.5);let a=Math.random()*Math.PI*2;obj.position.set(ship.position.x+Math.cos(a)*(25+Math.random()*12),3,ship.position.z+Math.sin(a)*(25+Math.random()*12));obj.position.clampLength(0,72);scene.add(obj);const health=(type==='brute'?65:25)+current.tier*9;enemies.push({obj,body,type,hp:health*(boss?5:1),boss,t:Math.random()*3,shot:1+Math.random()*2,charge:new THREE.Vector3()});}toast(wave===totalWaves&&current.boss?'Planetary guardian approaching!':`Wave ${wave} / ${totalWaves} · ${current.biome.mob}`);updateWave();}
function updateWave(){$('wave').textContent=`Wave ${wave} / ${totalWaves} · ${enemies.length} hostiles`;$('waveBar').style.width=(totalEnemies?kills/totalEnemies*100:0)+'%';}
function shot(position,direction,enemy=false,damage=10){const obj=mesh(bulletGeo,enemy?0xff776b:0xc3ffe3,scene,...position.toArray(),true);if(!enemy)obj.scale.set(.8,.8,2);bullets.push({obj,velocity:direction.clone().multiplyScalar(enemy?17+current.tier:65),life:enemy?5:1.8,enemy,damage});}
function burst(pos,color,n=16){for(let i=0;i<n;i++){const obj=mesh(sparkGeo,color,scene,...pos.toArray(),true);particles.push({obj,v:new THREE.Vector3((Math.random()-.5)*14,(Math.random()-.3)*9,(Math.random()-.5)*14),life:.5+Math.random()*.5});}}
function defeat(index){const e=enemies[index];burst(e.obj.position,current.biome.color,e.boss?45:15);const obj=mesh(crystalGeo,0xc9ffd5,scene,...e.obj.position.toArray(),true);drops.push({obj,value:e.boss?30:3+current.tier});remove(e.obj);enemies.splice(index,1);kills++;updateWave();if(!enemies.length){if(wave>=totalWaves)secure();else spawnTimer=2.5;}}
function secure(){clearedThisVisit=true;const first=!save.cleared.includes(current.id);if(first)save.cleared.push(current.id);const reward=(first?90:35)+current.tier*20;save.credits+=reward;persist();$('objective').textContent='World secured ✓';$('wave').textContent='All hostiles defeated';$('enemyInfo').textContent='Open the map to explore your next world.';toast(save.cleared.length===48?'All 48 worlds secured. You are a legend of the frontier!':`World secured! +${reward} crystals. Press M to explore.`);hud();}
function damage(amount){if(invulnerable>0)return;hp=Math.max(0,hp-amount);invulnerable=.65;burst(ship.position,0xffa588,6);if(hp===0){mode='dead';$('pauseTitle').textContent='The stars can wait.';$('pauseText').textContent='Your upgrades and discoveries are safe. Repair and try again.';$('resume').textContent='Repair & retry';$('pause').classList.remove('hidden');}hud();}
function nova(){if(mode!=='playing'||novaCooldown>0)return;novaCooldown=14;burst(ship.position,0xbcffd1,60);for(let i=enemies.length-1;i>=0;i--)if(enemies[i].obj.position.distanceTo(ship.position)<25){enemies[i].hp-=90+save.weapon*22;if(enemies[i].hp<=0)defeat(i);}for(let i=bullets.length-1;i>=0;i--)if(bullets[i].enemy){remove(bullets[i].obj);bullets.splice(i,1);}toast('Nova pulse released!');}
function openMap(){if(!started)return;mode=mode==='dead'?'deadmap':'map';firing=false;for(const k in keys)keys[k]=false;$('pause').classList.add('hidden');$('map').classList.remove('hidden');renderMap();}
function closeMap(){$('map').classList.add('hidden');if(mode==='deadmap'){mode='dead';$('pause').classList.remove('hidden');}else mode='playing';}
function renderMap(){$('mapCount').textContent=save.cleared.length+' / 48';$('planetGrid').innerHTML='';for(const p of planets){const b=document.createElement('button');b.className='planet'+(selected===p.id?' selected':'');b.style.setProperty('--color','#'+p.biome.color.toString(16).padStart(6,'0'));b.innerHTML=`<span class="orb"></span><strong>${p.name}</strong><small>${String(p.id+1).padStart(2,'0')} · LEVEL ${p.tier}</small>${save.cleared.includes(p.id)?'<span class="check">✓</span>':''}`;b.onclick=()=>{selected=p.id;renderMap();};$('planetGrid').appendChild(b);}const p=planets[selected];$('selection').innerHTML=`${p.name}<br><span>${p.biome.name} · Level ${p.tier}<br>${p.biome.mob}${p.boss?' + guardian':''}</span>`;for(const kind of ['weapon','shield']){const level=save[kind],cost=level*100;$(kind+'Upgrade').textContent=`${kind==='weapon'?'Plasma cannon':'Hull plating'} MK ${level} ${level>=8?' · MAX':`↑ ◈ ${cost}`}`;$(kind+'Upgrade').disabled=level>=8||save.credits<cost;}hud();}
function upgrade(kind){const cost=save[kind]*100;if(save.credits<cost||save[kind]>=8)return;save.credits-=cost;save[kind]++;persist();renderMap();toast('Ship upgraded. Ready for the next horizon.');}
function pause(){if(mode==='playing'){mode='paused';firing=false;$('pauseTitle').textContent='Drifting among stars.';$('pauseText').textContent='Your expedition will be right here.';$('resume').textContent='Resume flight';$('pause').classList.remove('hidden');}else if(mode==='paused'){mode='playing';$('pause').classList.add('hidden');}}
$('start').onclick=()=>beginPlanet(save.last);$('mapButton').onclick=openMap;$('closeMap').onclick=closeMap;$('warp').onclick=()=>beginPlanet(selected);$('weaponUpgrade').onclick=()=>upgrade('weapon');$('shieldUpgrade').onclick=()=>upgrade('shield');$('pauseButton').onclick=pause;$('resume').onclick=()=>mode==='dead'?beginPlanet(current.id):pause();$('pauseMap').onclick=openMap;
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='KeyM'){if(mode==='map'||mode==='deadmap')closeMap();else if(started)openMap();}if(e.code==='Escape'){if(mode==='map'||mode==='deadmap')closeMap();else pause();}if(e.code==='KeyE')nova();});window.addEventListener('keyup',e=>keys[e.code]=false);
renderer.domElement.addEventListener('pointermove',e=>{pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);});renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===0&&mode==='playing')firing=true;});window.addEventListener('pointerup',()=>firing=false);window.addEventListener('blur',()=>{for(const k in keys)keys[k]=false;firing=false;if(mode==='playing')pause();});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
const move=new THREE.Vector3(),direction=new THREE.Vector3(),cameraTarget=new THREE.Vector3();
function update(dt){elapsed+=dt;fireTimer-=dt;invulnerable-=dt;novaCooldown=Math.max(0,novaCooldown-dt);ship.visible=invulnerable<=0||Math.floor(elapsed*16)%2===0;
 move.set((keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),0,(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0));const boosting=keys.ShiftLeft||keys.ShiftRight;if(move.lengthSq())ship.position.addScaledVector(move.normalize(),dt*(boosting?29:17));const radius=Math.hypot(ship.position.x,ship.position.z);if(radius>74){ship.position.x*=74/radius;ship.position.z*=74/radius;}ship.position.y=3+Math.sin(elapsed*3)*.12;
 ray.setFromCamera(pointer,camera);ray.ray.intersectPlane(plane,aim);direction.copy(aim).sub(ship.position);direction.y=0;if(direction.lengthSq()<.01)direction.set(0,0,-1);direction.normalize();ship.rotation.y=Math.atan2(-direction.x,-direction.z);ship.rotation.z=-move.x*.12;
 if((firing||keys.Space)&&fireTimer<=0){fireTimer=.18-Math.min(save.weapon-1,7)*.012;const origin=ship.position.clone().addScaledVector(direction,2.2);shot(origin,direction,false,17+save.weapon*8);if(save.weapon>=4){for(const angle of [-.1,.1])shot(origin,direction.clone().applyAxisAngle(new THREE.Vector3(0,1,0),angle),false,10+save.weapon*4);}}
 if(!enemies.length&&!clearedThisVisit){spawnTimer-=dt;if(spawnTimer<=0)spawnWave();}
 for(const e of enemies){e.t+=dt;e.shot-=dt;const d=ship.position.clone().sub(e.obj.position);d.y=0;const dist=d.length();d.normalize();let speed=4+current.tier*.25;if(e.type==='swarm')speed=8+current.tier*.3;if(e.type==='brute')speed=3;if(e.type==='wisp'){d.applyAxisAngle(new THREE.Vector3(0,1,0),Math.sin(e.t*2)*1.2);speed=9;}if(e.type==='charger'){if(e.t>3){e.t=0;e.charge.copy(d);}if(e.t<.65&&e.charge.lengthSq()){d.copy(e.charge);speed=26;}else speed=3;}
 if(e.type==='shooter'||e.type==='jelly'){speed=dist>22?5:dist<14?-4:0;if(e.shot<=0){e.shot=e.type==='jelly'?2.2:1.6;shot(e.obj.position,d,true,10+current.tier);if(e.type==='shooter')for(const a of [-.2,.2])shot(e.obj.position,d.clone().applyAxisAngle(new THREE.Vector3(0,1,0),a),true,8+current.tier);}}
 if(e.boss){speed*=.7;if(e.shot<=0){e.shot=1.8;for(let j=0;j<10;j++)shot(e.obj.position,new THREE.Vector3(Math.cos(j*Math.PI/5),0,Math.sin(j*Math.PI/5)),true,14);}}
 e.obj.position.addScaledVector(d,speed*dt);e.obj.position.y=3+Math.sin(e.t*3)*.45;e.body.rotation.y+=dt;e.obj.rotation.y=Math.atan2(-d.x,-d.z);if(dist<(e.boss?4.6:2.3))damage(e.type==='brute'?22:12);}
 for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.life-=dt;b.obj.position.addScaledVector(b.velocity,dt);let hit=false;if(b.enemy){if(b.obj.position.distanceTo(ship.position)<1.6){damage(b.damage);hit=true;}}else for(let j=enemies.length-1;j>=0;j--){const e=enemies[j];if(b.obj.position.distanceTo(e.obj.position)<(e.boss?4:e.type==='brute'?2:1.65)){e.hp-=b.damage;hit=true;if(e.hp<=0)defeat(j);break;}}if(hit||b.life<=0){remove(b.obj);bullets.splice(i,1);}}
 for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.obj.rotation.y+=dt*2;const v=ship.position.clone().sub(d.obj.position);if(v.length()<16||clearedThisVisit)d.obj.position.addScaledVector(v.normalize(),dt*23);if(d.obj.position.distanceTo(ship.position)<2){save.credits+=d.value;remove(d.obj);drops.splice(i,1);persist();}}
 for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.obj.position.addScaledVector(p.v,dt);p.obj.scale.setScalar(Math.max(.01,p.life));if(p.life<=0){remove(p.obj);particles.splice(i,1);}}
 hud();}
createWorld(current);hud();let last=performance.now();
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.035);last=now;if(mode==='playing')update(dt);else if(mode==='welcome'){elapsed+=dt;ship.rotation.y=Math.sin(elapsed*.3)*.3;ship.position.y=3+Math.sin(elapsed)*.4;}if(noticeTimer>0){noticeTimer-=dt;if(noticeTimer<=0)$('notice').classList.remove('show');}
 cameraTarget.set(ship.position.x,ship.position.y+34,ship.position.z+40);camera.position.lerp(cameraTarget,1-Math.exp(-dt*5));camera.lookAt(ship.position.x,0,ship.position.z-9);distant.rotation.y+=dt*.018;renderer.render(scene,camera);}
requestAnimationFrame(frame);
