'use strict';
const $=id=>document.getElementById(id);
const biomes=[
 {name:'Emerald Reach',color:0x57c68b,ground:0x123e34,fog:0x09272c,mob:'Spore swarm',type:'swarm'},
 {name:'Glacial Veil',color:0x8ddcf4,ground:0x294e68,fog:0x142b48,mob:'Frost sentinels',type:'shooter'},
 {name:'Ember Expanse',color:0xff8559,ground:0x512b2b,fog:0x301923,mob:'Magma brutes',type:'brute'},
 {name:'Amethyst Drift',color:0xb899ff,ground:0x392c60,fog:0x201b3c,mob:'Phase wisps',type:'wisp'},
 {name:'Golden Dunes',color:0xf0cf7b,ground:0x58482d,fog:0x322b21,mob:'Dune stalkers',type:'charger'},
 {name:'Tidal Frontier',color:0x56e6d7,ground:0x124d5a,fog:0x0a2b3c,mob:'Storm jellies',type:'jelly'}
];
const names=['Verdant Echo','Frosthaven','Cinder IX','Violet Moon','Solara','Pelagic Blue','Mosslight','Aurora Shelf','Ashen Crown','Prism Hollow','Dusthaven','Coral Night','Fernfall','Boreal Rift','Emberheart','Dreamglass','Saffron Sea','Deepwater','Canopy Prime','Winter Halo','Obsidian Sun','Amethyst Arc','Amber Reach','Pearl Abyss','Clover Vale','Icebound Eden','Molten Gate','Ghost Orchid','Ochre Moon','Siren Reef','Wildgrove','Snowblind','Flarepoint','Velvet Comet','Gilded Dusk','Azure Bloom','Jade Horizon','Polar Crown','Pyre World','Lilac Vortex','Sunken Gold','Opal Tide','Eden Beyond','Absolute Zero','Inferno Ultima','Astral Throne','Last Oasis','Ocean Eternal'];
const frontierNames=['Aether','Nyx','Halcyon','Kepler','Vesper','Elysium','Titan','Zenith'];for(const n of frontierNames)for(const suffix of ['Prime','Reach','Haven','Rift','Crown','Beyond'])names.push(n+' '+suffix);
const PLANET_COUNT=names.length;
const planets=names.map((name,i)=>({name,id:i,biome:biomes[i%6],tier:Math.min(12,Math.floor(i/6)+1),boss:(i+1)%4===0}));
let save={credits:0,weapon:1,shield:1,cleared:[],last:0};
try{const s=JSON.parse(localStorage.getItem('starfarer-save-v1'));if(s&&Array.isArray(s.cleared))save={credits:Math.max(0,Number(s.credits)||0),weapon:Math.max(1,Math.min(8,Number(s.weapon)||1)),shield:Math.max(1,Math.min(8,Number(s.shield)||1)),cleared:s.cleared.filter(n=>Number.isInteger(n)&&n>=0&&n<PLANET_COUNT),last:Math.max(0,Math.min(PLANET_COUNT-1,Number(s.last)||0))};}catch{}
let storageWarned=false;function persist(){try{localStorage.setItem('starfarer-save-v1',JSON.stringify(save));}catch{if(!storageWarned){toast('Saving is unavailable in this browser. You can still play.');storageWarned=true;}}}
const scene=new THREE.Scene();scene.background=new THREE.Color(0x01030a);
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('overlay').innerHTML='<div class="dialog"><h2>3D rendering is unavailable.</h2><p>Please enable graphics acceleration in your browser.</p></div>';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;$('scene').appendChild(renderer.domElement);
const effects=createSpaceEffects(renderer);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.25,100000);
scene.add(new THREE.AmbientLight(0x819fdf,.55));const sunLight=new THREE.DirectionalLight(0xffedcf,3.5);sunLight.position.set(-1000,600,900);scene.add(sunLight);const rimLight=new THREE.DirectionalLight(0x548bff,1.5);rimLight.position.set(100,-10,-100);scene.add(rimLight);
const V=THREE.Vector3, Q=THREE.Quaternion;const forwardAxis=new V(0,0,-1),upAxis=new V(0,1,0),rightAxis=new V(1,0,0);
let seed=91743;function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}
function makeMesh(geo,color,parent=scene,pos=new V(),glow=0){const obj=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,metalness:.45,roughness:.42,emissive:color,emissiveIntensity:glow}));obj.position.copy(pos);parent.add(obj);return obj;}
function glowTexture(){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d'),g=ctx.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.12,'rgba(220,245,255,.95)');g.addColorStop(.3,'rgba(130,200,255,.3)');g.addColorStop(1,'rgba(60,120,255,0)');ctx.fillStyle=g;ctx.fillRect(0,0,128,128);return new THREE.CanvasTexture(c);}
const glowMap=glowTexture();function glow(parent,color,size,pos=new V(),opacity=1){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:glowMap,color,transparent:true,opacity,blending:THREE.AdditiveBlending,depthWrite:false}));s.scale.set(size,size,1);s.position.copy(pos);parent.add(s);return s;}
// A procedural galactic backdrop, generated locally once and viewed from inside a sphere.
const skyCanvas=document.createElement('canvas');skyCanvas.width=2048;skyCanvas.height=1024;const skyCtx=skyCanvas.getContext('2d');skyCtx.fillStyle='#01030a';skyCtx.fillRect(0,0,2048,1024);
for(let i=0;i<680;i++){const x=rand()*2048,y=512+Math.sin(x/2048*Math.PI*4)*110+(rand()-.5)*220,r=30+rand()*160;const g=skyCtx.createRadialGradient(x,y,0,x,y,r);const color=i%3===0?'125,67,135':i%3===1?'36,97,140':'75,94,139';g.addColorStop(0,`rgba(${color},.045)`);g.addColorStop(1,`rgba(${color},0)`);skyCtx.fillStyle=g;skyCtx.fillRect(x-r,y-r,r*2,r*2);}
for(let i=0;i<11000;i++){const x=rand()*2048,y=rand()*1024,r=rand()<.015?1.2:.25+rand()*.45;skyCtx.fillStyle=`rgba(210,225,255,${.13+rand()*.75})`;skyCtx.beginPath();skyCtx.arc(x,y,r,0,Math.PI*2);skyCtx.fill();}
const skyTex=new THREE.CanvasTexture(skyCanvas);skyTex.colorSpace=THREE.SRGBColorSpace;const sky=new THREE.Mesh(new THREE.SphereGeometry(44000,32,20),new THREE.MeshBasicMaterial({map:skyTex,side:THREE.BackSide,depthWrite:false}));sky.rotation.z=.32;scene.add(sky);
const starPositions=[],starColors=[];for(let i=0;i<4200;i++){const d=new V(rand()-.5,rand()-.5,rand()-.5).normalize().multiplyScalar(20000+rand()*16000);starPositions.push(...d.toArray());const c=new THREE.Color().setHSL(.52+rand()*.18,.15+rand()*.3,.55+rand()*.4);starColors.push(c.r,c.g,c.b);}const starGeo=new THREE.BufferGeometry();starGeo.setAttribute('position',new THREE.Float32BufferAttribute(starPositions,3));starGeo.setAttribute('color',new THREE.Float32BufferAttribute(starColors,3));const stars=new THREE.Points(starGeo,new THREE.PointsMaterial({size:95,vertexColors:true,map:glowMap,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));scene.add(stars);
const sun=makeMesh(new THREE.SphereGeometry(260,40,24),0xffdeb0,scene,new V(-8500,3000,-16000),5);glow(sun,0xffbb76,2400);glow(sun,0xffeacb,950);
// Continuous 3D positions: selecting a destination never moves the ship.
planets.forEach((p,i)=>{const angle=i*2.39996,r=3000+Math.pow(i,.83)*760;p.radius=190+rand()*200;p.pos=new V(Math.cos(angle)*r,(rand()-.5)*3000,Math.sin(angle)*r-2800);});
planets[0].pos.set(300,80,-1700);planets[0].radius=330;planets[1].pos.set(-1800,400,-3400);planets[1].radius=390;planets[2].pos.set(2000,-450,-4200);planets[2].radius=300;planets[3].pos.set(3200,750,-6100);
const noiseGLSL=`
float hash(vec3 p){p=fract(p*.3183099+vec3(.1,.2,.3));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}
float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}
float fbm(vec3 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=noise(p)*a;p=p*2.03+vec3(9.2,1.7,6.3);a*=.5;}return v;}`;
// Smooth volumetric-looking nebula avoids enlarging a low-resolution sky image.
sky.material.dispose();skyTex.dispose();sky.material=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,vertexShader:'varying vec3 skyDir;void main(){skyDir=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 skyDir;${noiseGLSL}
void main(){vec3 d=normalize(skyDir);float band=exp(-pow((d.y+d.x*.28+.08)*3.4,2.));float n=fbm(d*5.+vec3(3.,8.,1.));float w=fbm(d*13.+vec3(17.,1.,5.));float cloud=pow(max(0.,n-.25),2.)*band;vec3 c=vec3(.0015,.0025,.007)+mix(vec3(.045,.15,.24),vec3(.28,.055,.23),smoothstep(.32,.65,w))*cloud*2.8;float dust=smoothstep(.43,.68,w);c*=1.-dust*.55;gl_FragColor=vec4(c,1.);
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`});
const planetVertex=`varying vec3 vPos;varying vec3 vNormal;varying vec3 vWorld;void main(){vPos=position;vNormal=normalize(mat3(modelMatrix)*normal);vWorld=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(vWorld,1.);}`;
const planetFragment=`uniform float kind;uniform float variant;uniform vec3 tint;varying vec3 vPos;varying vec3 vNormal;varying vec3 vWorld;${noiseGLSL}
void main(){vec3 p=normalize(vPos),n=normalize(vNormal);float f=fbm(p*3.3+vec3(fbm(p*5.+variant))*1.1+variant),detail=fbm(p*48.+variant),latitude=abs(p.y);vec3 c;
if(kind<.5){float land=smoothstep(.47,.51,f);vec3 ocean=mix(vec3(.002,.012,.052),vec3(.012,.09,.15),f*1.4);vec3 earth=mix(vec3(.009,.043,.023),vec3(.12,.19,.065),detail);earth=mix(earth,vec3(.34,.27,.12),smoothstep(.53,.67,f));c=mix(ocean,earth,land);c=mix(c,vec3(.8,.9,.95),smoothstep(.79,.93,latitude+(f-.5)*.24));}
else if(kind<1.5){c=mix(vec3(.055,.16,.26),vec3(.7,.85,.9),smoothstep(.25,.7,f));c*=.7+.5*detail;}
else if(kind<2.5){float lava=pow(1.-smoothstep(.018,.07,abs(f-.47)),2.);c=mix(vec3(.04,.025,.028)*(detail+1.),vec3(2.3,.27,.018),lava);}
else if(kind<3.5){float bands=sin(p.y*32.+fbm(p*5.+variant)*13.+sin(p.x*11.)*.7)*.5+.5;c=mix(vec3(.13,.065,.23),vec3(.55,.36,.68),bands)*(.65+detail*.6);}
else if(kind<4.5){float bands=sin(p.y*65.+f*12.)*.5+.5;c=mix(vec3(.27,.12,.045),vec3(.72,.52,.28),bands*.4+f*.65);}
else{c=mix(vec3(.006,.045,.14),vec3(.025,.32,.4),f);c=mix(c,vec3(.35,.65,.64),smoothstep(.57,.62,f));}
float relief=noise(p*180.+variant);c*=.86+detail*.28+relief*.1;vec3 grain=vec3(noise(p*95.+1.),noise(p*95.+7.),noise(p*95.+19.))-.5;n=normalize(n+grain*(kind>1.5&&kind<2.5?.15:.028));float diffuse=max(dot(n,normalize(vec3(-.5,.35,.85))),0.);vec3 viewDir=normalize(cameraPosition-vWorld);float spec=pow(max(dot(reflect(-normalize(vec3(-.5,.35,.85)),n),viewDir),0.),60.);if(kind<.5||kind>4.5)c+=vec3(.35,.5,.6)*spec*(1.-smoothstep(.47,.51,f));c*=.025+diffuse*1.35;if(kind<.5){float cities=pow(noise(p*260.+variant),24.)*smoothstep(.5,.54,f);c+=vec3(1.,.48,.12)*cities*(1.-smoothstep(0.,.22,diffuse))*.7;}float rim=pow(1.-max(dot(n,viewDir),0.),3.5);c+=tint*rim*.25*diffuse;gl_FragColor=vec4(c,1.);#include <tonemapping_fragment>\n#include <colorspace_fragment>}`.replace(';#include',';\n#include');
const atmosphereFragment=`uniform vec3 tint;varying vec3 vNormal;varying vec3 vWorld;void main(){vec3 n=normalize(vNormal);float facing=max(dot(n,normalize(cameraPosition-vWorld)),0.);float rim=pow(1.-facing,4.);float lit=.25+.75*max(dot(n,normalize(vec3(-.5,.35,.85))),0.);gl_FragColor=vec4(tint,rim*.65*lit);}`;
const planetGeo=new THREE.SphereGeometry(1,80,48),distantPlanetGeo=new THREE.SphereGeometry(1,24,16);const cloudFragment=`uniform float variant;varying vec3 vPos;varying vec3 vNormal;varying vec3 vWorld;${noiseGLSL}
void main(){vec3 p=normalize(vPos);float weather=fbm(p*7.+vec3(variant,3.,7.)+vec3(fbm(p*4.))*2.);float cover=smoothstep(.54,.7,weather);float sunlight=max(dot(normalize(vNormal),normalize(vec3(-.5,.35,.85))),0.);gl_FragColor=vec4(vec3(.77,.84,.94)*(.04+sunlight*1.3),cover*.87);}`;
const moonGeo=new THREE.SphereGeometry(1,24,16);const moons=[];
for(const p of planets){const group=new THREE.Group();group.position.copy(p.pos);scene.add(group);p.group=group;
 const material=new THREE.ShaderMaterial({vertexShader:planetVertex,fragmentShader:planetFragment,uniforms:{kind:{value:p.id%6},variant:{value:p.id*2.31},tint:{value:new THREE.Color(p.biome.color)}}});p.mesh=new THREE.Mesh(planetGeo,material);p.mesh.scale.setScalar(p.radius);group.add(p.mesh);if(p.id%6<2||p.id%6===5){p.clouds=new THREE.Mesh(planetGeo,new THREE.ShaderMaterial({vertexShader:planetVertex,fragmentShader:cloudFragment,uniforms:{variant:{value:p.id*2.31}},transparent:true,depthWrite:false}));p.clouds.scale.setScalar(p.radius*1.012);group.add(p.clouds);}
 const atmosphere=new THREE.Mesh(planetGeo,new THREE.ShaderMaterial({vertexShader:planetVertex,fragmentShader:atmosphereFragment,uniforms:{tint:{value:new THREE.Color(p.biome.color)}},transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));p.atmosphere=atmosphere;atmosphere.scale.setScalar(p.radius*1.028);group.add(atmosphere);
 if(p.id%4===1){const ringGeo=new THREE.RingGeometry(p.radius*1.4,p.radius*2.25,120,1);const ringMat=new THREE.ShaderMaterial({side:THREE.DoubleSide,transparent:true,depthWrite:false,uniforms:{inner:{value:p.radius*1.4},outer:{value:p.radius*2.25},tint:{value:new THREE.Color(p.id===1?0xc7bba2:p.biome.color)}},vertexShader:'varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform float inner;uniform float outer;uniform vec3 tint;varying vec3 v;void main(){float r=length(v.xy);float t=(r-inner)/(outer-inner);float bands=.6+.12*sin(t*170.)+.12*sin(t*67.);float gap=smoothstep(0.,.015,abs(t-.57));gl_FragColor=vec4(tint*(.5+bands*.35),max(0.,bands)*gap*.85);}'});const ring=new THREE.Mesh(ringGeo,ringMat);ring.rotation.set(1.22,.16,.2);group.add(ring);}
 if(p.id%3===0){const moon=makeMesh(moonGeo,0x8c919c,group,new V(-p.radius*2.1,p.radius*.6,p.radius*.7));moon.scale.setScalar(p.radius*.17);moons.push(moon);}
}
// Asteroids share one mesh draw call, with real depth and parallax.
const asteroids=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),new THREE.MeshStandardMaterial({color:0x777575,roughness:1}),1100);const dummy=new THREE.Object3D();for(let i=0;i<1100;i++){const a=rand()*Math.PI*2,r=1050+rand()*480;dummy.position.set(-1800+Math.cos(a)*r,400+(rand()-.5)*160,-3400+Math.sin(a)*r);dummy.rotation.set(rand()*6,rand()*6,rand()*6);dummy.scale.set(3+rand()*10,2+rand()*7,3+rand()*10);dummy.updateMatrix();asteroids.setMatrixAt(i,dummy.matrix);}scene.add(asteroids);
const ship=new THREE.Group();scene.add(ship);const shipModel=new THREE.Group();ship.add(shipModel);
const body=makeMesh(new THREE.CylinderGeometry(.55,1.1,5.8,8),0xb6c9db,shipModel,new V(0,0,.3));body.rotation.x=Math.PI/2;
const nose=makeMesh(new THREE.ConeGeometry(.57,2.7,8),0xe7f2fa,shipModel,new V(0,0,-3.7));nose.rotation.x=-Math.PI/2;
const cockpit=makeMesh(new THREE.SphereGeometry(1,16,12),0x2383ad,shipModel,new V(0,.7,-1.25),.3);cockpit.scale.set(.64,.4,1.4);cockpit.material.metalness=.9;cockpit.material.roughness=.15;
const wingGeometry=new THREE.BufferGeometry();wingGeometry.setAttribute('position',new THREE.Float32BufferAttribute([.5,0,-1,5.4,-.25,2.9,.7,0,2.1,.5,-.17,-1,.7,-.17,2.1,5.4,-.42,2.9,.5,0,-1,.5,-.17,-1,5.4,-.42,2.9,.5,0,-1,5.4,-.42,2.9,5.4,-.25,2.9],3));wingGeometry.computeVertexNormals();
const engines=[];for(const side of [-1,1]){const wing=makeMesh(wingGeometry,0x8199b1,shipModel);wing.scale.x=side;wing.material.side=THREE.DoubleSide;const nacelle=makeMesh(new THREE.CylinderGeometry(.42,.55,3.4,12),0x41566f,shipModel,new V(side*2.9,-.1,1.6));nacelle.rotation.x=Math.PI/2;makeMesh(new THREE.BoxGeometry(.15,.12,2),0x78e9ff,shipModel,new V(side*2.9,.36,1.2),2);const exhaust=glow(shipModel,0x69cfff,3,new V(side*2.9,-.1,3.45));engines.push(exhaust);const flame=makeMesh(new THREE.ConeGeometry(.4,3.5,10),0x77e6ff,shipModel,new V(side*2.9,-.1,5.1),3);flame.rotation.x=Math.PI/2;engines.push(flame);makeMesh(new THREE.BoxGeometry(.14,.15,.7),side<0?0xff6262:0x74ffba,shipModel,new V(side*4.8,-.15,2.6),3);}
for(const side of [-1,1]){for(let j=0;j<4;j++){const panel=makeMesh(alienGeometry.box,0x23394e,shipModel,new V(side*(1.3+j*.65),.02,1.1+j*.25));panel.scale.set(.38,.09,1.2);}const barrel=makeMesh(alienGeometry.tube,0x536d83,shipModel,new V(side*2.9,-.05,-.8));barrel.scale.set(.18,2.4,.18);barrel.rotation.x=Math.PI/2;glow(shipModel,0x68ddff,.9,new V(side*2.9,-.05,-2),.8);}
const fin=makeMesh(new THREE.BoxGeometry(.13,1.6,1.9),0x6f8ca8,shipModel,new V(0,1.15,1.9));fin.rotation.x=-.3;
const exhaustLight=new THREE.PointLight(0x4ac8ff,12,18);exhaustLight.position.set(0,0,4);ship.add(exhaustLight);
// Close dust becomes long luminous streaks during cruise.
const dustArray=new Float32Array(240*6);const dustGeo=new THREE.BufferGeometry();dustGeo.setAttribute('position',new THREE.BufferAttribute(dustArray,3));const dust=new THREE.LineSegments(dustGeo,new THREE.LineBasicMaterial({color:0x99d9ff,transparent:true,opacity:.35,blending:THREE.AdditiveBlending,depthWrite:false}));scene.add(dust);
const dustSeeds=Array.from({length:240},()=>new V((rand()-.5)*500,(rand()-.5)*350,-rand()*800));
let mode='welcome',started=false,selected=0,target=planets[0],current=null,hp=100,speed=0,elapsed=0,fireTimer=0,novaCooldown=0,invulnerable=0,noticeTimer=0,autoPilot=false,combatIdle=20,wave=0,kills=0,totalEnemies=0,spawnTimer=0;
const completed=new Set(save.cleared),encounters=new Map(),enemies=[],bullets=[],particles=[],keys={};let firing=false;const steer=new THREE.Vector2(),turnRate=new THREE.Vector2(),mouseMotion=new THREE.Vector2();const forward=new V(0,0,-1),right=new V(1,0,0),up=new V(0,1,0);let aimTarget=null;
const enemyShapes={swarm:new THREE.IcosahedronGeometry(3,0),shooter:new THREE.OctahedronGeometry(4),brute:new THREE.DodecahedronGeometry(5,0),wisp:new THREE.TorusKnotGeometry(2.5,.7,32,6),charger:new THREE.ConeGeometry(3,8,4),jelly:new THREE.SphereGeometry(4,12,8)};
const bulletGeo=new THREE.CylinderGeometry(.25,.25,7,6),sparkGeo=new THREE.IcosahedronGeometry(.55,0);
function toast(text){$('notice').textContent=text;$('notice').classList.add('show');noticeTimer=5;}
function maxHp(){return 100+(save.shield-1)*30;}
function disposeObject(obj){obj.traverse(c=>{if(c.material){if(Array.isArray(c.material))c.material.forEach(m=>m.dispose());else c.material.dispose();}});obj.removeFromParent();}
function clearObjects(list){for(const e of list)disposeObject(e.obj);list.length=0;}
function resetFlight(){steer.set(0,0);turnRate.set(0,0);mouseMotion.set(0,0);encounters.clear();clearObjects(enemies);clearObjects(bullets);clearObjects(particles);current=null;ship.position.set(0,0,0);ship.quaternion.identity();forward.copy(forwardAxis);right.copy(rightAxis);up.copy(upAxis);speed=0;hp=maxHp();autoPilot=false;combatIdle=20;invulnerable=3;target=planets[0];selected=0;camera.position.set(0,5,22);camera.quaternion.identity();}
function start(){resetFlight();mode='playing';started=true;['overlay','pause','map'].forEach(id=>$(id).classList.add('hidden'));toast('W to fly · Mouse to steer · Shift for cruise · F for autopilot');}
function setTarget(id){target=planets[id];selected=id;closeMap();autoPilot=false;toast('Course set: '+target.name+'. Fly toward the diamond, or press F for autopilot.');}
function openMap(){if(!started||mode==='dead')return;mode='map';if(document.pointerLockElement)document.exitPointerLock();firing=false;steer.set(0,0);turnRate.set(0,0);mouseMotion.set(0,0);for(const k in keys)keys[k]=false;$('pause').classList.add('hidden');$('map').classList.remove('hidden');renderMap();}
function closeMap(){$('map').classList.add('hidden');mode='playing';}
function renderMap(){const scroll=$('planetGrid').scrollTop;$('mapCount').textContent=save.cleared.length+' / '+PLANET_COUNT+' secured';$('planetGrid').innerHTML='';for(const p of planets){const b=document.createElement('button');b.className='planet'+(selected===p.id?' selected':'');b.style.setProperty('--color','#'+p.biome.color.toString(16).padStart(6,'0'));b.innerHTML=`<span class="orb"></span><strong>${p.name}</strong><small>${formatDistance(ship.position.distanceTo(p.pos))} · LV ${p.tier}</small>${completed.has(p.id)?'<span class="check">✓</span>':''}`;b.onclick=()=>{selected=p.id;renderMap();};$('planetGrid').appendChild(b);}$('planetGrid').scrollTop=scroll;const p=planets[selected];$('selection').innerHTML=`${p.name}<br><span>${p.biome.name} · Level ${p.tier}<br>${p.biome.mob}${p.boss?' + guardian':''}<br>${formatDistance(ship.position.distanceTo(p.pos)-p.radius)} to atmosphere</span>`;for(const k of ['weapon','shield']){const level=save[k],cost=level*100;$(k+'Upgrade').textContent=`${k==='weapon'?'Plasma cannon':'Hull plating'} MK ${level}${level===8?' · MAX':` ↑ ◈ ${cost}`}`;$(k+'Upgrade').disabled=level===8||save.credits<cost;}hud();}
function upgrade(kind){const cost=save[kind]*100;if(save.credits<cost||save[kind]>=8)return;save.credits-=cost;save[kind]++;if(kind==='shield')hp+=30;persist();renderMap();toast('Upgrade installed.');}
function pause(){if(mode==='playing'){mode='paused';if(document.pointerLockElement)document.exitPointerLock();firing=false;steer.set(0,0);turnRate.set(0,0);mouseMotion.set(0,0);$('pauseTitle').textContent='Drifting among stars.';$('pauseText').textContent='Flight controls: W thrust · S brake · A/D strafe · Q/R down/up · Mouse or arrows steer · Shift cruise · F autopilot · E nova.';$('resume').textContent='Resume flight';$('pauseMap').style.display='';$('pause').classList.remove('hidden');}else if(mode==='paused'){mode='playing';$('pause').classList.add('hidden');}}
function formatDistance(n){return n>=1000?(n/1000).toFixed(1)+' km':Math.max(0,Math.round(n))+' m';}
function getEncounter(p){if(!encounters.has(p.id))encounters.set(p.id,{wave:0,cleared:completed.has(p.id)});return encounters.get(p.id);}
function enterOrbit(p){if(current===p)return;if(current&&!getEncounter(current).cleared&&enemies.length)getEncounter(current).wave=Math.max(0,getEncounter(current).wave-1);clearObjects(enemies);clearObjects(bullets);current=p;const encounter=getEncounter(p);wave=encounter.wave;kills=0;totalEnemies=0;spawnTimer=3;save.last=p.id;persist();if(encounter.cleared)toast(p.name+' · Orbit secured. Enjoy the view.');else toast('Entering '+p.name+' orbit. Alien fleet detected.');}
function spawnWave(){if(!current||getEncounter(current).cleared)return;const enc=getEncounter(current);wave=++enc.wave;kills=0;totalEnemies=4+current.tier+wave;const totalWaves=current.tier>4?3:2;
 for(let i=0;i<totalEnemies;i++){const type=current.biome.type,boss=current.boss&&wave===totalWaves&&i===0,visual=buildAlien(type,current.biome.color,boss),obj=visual.obj,body=visual.body;
 const a=i/totalEnemies*Math.PI*2,dir=forward.clone().multiplyScalar(110+rand()*90).addScaledVector(right,Math.cos(a)*90).addScaledVector(up,Math.sin(a)*70);obj.position.copy(ship.position).add(dir);const fromPlanet=obj.position.clone().sub(current.pos);if(fromPlanet.length()<current.radius+35)obj.position.copy(current.pos).add(fromPlanet.normalize().multiplyScalar(current.radius+45));scene.add(obj);enemies.push({obj,body,type,boss,hp:((type==='brute'?105:38)+current.tier*13)*(boss?4:1),maxHp:((type==='brute'?105:38)+current.tier*13)*(boss?4:1),velocity:new V(),t:rand()*3,shot:2+rand()*2,charge:new V()});}
 toast(current.boss&&wave===totalWaves?'Guardian ship entering orbit!':`${current.biome.mob} · Fleet ${wave} / ${totalWaves}`);}
function shot(pos,dir,enemy=false,damageAmount=10){const obj=makeMesh(bulletGeo,enemy?0xff6553:0x7af0ff,scene,pos,4);obj.quaternion.setFromUnitVectors(upAxis,dir);bullets.push({obj,velocity:dir.clone().multiplyScalar(enemy?115:480+speed),life:enemy?5:2.5,enemy,damage:damageAmount,previous:pos.clone()});}
function burst(pos,color,count=20){for(let i=0;i<count;i++){const obj=makeMesh(sparkGeo,color,scene,pos,3);particles.push({obj,v:new V(rand()-.5,rand()-.5,rand()-.5).multiplyScalar(65),life:.6+rand()*.7});}const flash=glow(scene,color,35,pos);particles.push({obj:flash,v:new V(),life:.45,sprite:true});}
function defeat(index){const e=enemies[index];burst(e.obj.position,current.biome.color,e.boss?55:24);save.credits+=e.boss?45:5+current.tier;disposeObject(e.obj);enemies.splice(index,1);kills++;if(!enemies.length){const totalWaves=current.tier>4?3:2;if(wave>=totalWaves){getEncounter(current).cleared=true;completed.add(current.id);if(!save.cleared.includes(current.id))save.cleared.push(current.id);const reward=100+current.tier*30;save.credits+=reward;hp=Math.min(maxHp(),hp+45);toast(save.cleared.length===PLANET_COUNT?'All '+PLANET_COUNT+' worlds liberated. The universe is yours!':`${current.name} secured! +${reward} crystals. Keep exploring.`);}else spawnTimer=4;}persist();}
function damage(amount){if(invulnerable>0||mode!=='playing')return;hp=Math.max(0,hp-amount);invulnerable=.6;combatIdle=0;burst(ship.position,0xff8b63,8);if(hp===0){mode='dead';if(document.pointerLockElement)document.exitPointerLock();autoPilot=false;speed=0;$('pauseTitle').textContent='Rescue beacon received.';$('pauseText').textContent='Your discoveries and upgrades are safe. Launch a repaired ship from the starting point.';$('resume').textContent='Repair & relaunch';$('pauseMap').style.display='none';$('pause').classList.remove('hidden');}}
function nova(){if(mode!=='playing'||novaCooldown>0)return;novaCooldown=14;burst(ship.position,0x80e5ff,65);for(let i=enemies.length-1;i>=0;i--)if(enemies[i].obj.position.distanceTo(ship.position)<190){enemies[i].hp-=110+save.weapon*25;if(enemies[i].hp<=0)defeat(i);}for(let i=bullets.length-1;i>=0;i--)if(bullets[i].enemy){disposeObject(bullets[i].obj);bullets.splice(i,1);}toast('Nova pulse · nearby hostiles hit');}
function toggleAuto(){if(mode!=='playing')return;autoPilot=!autoPilot;steer.set(0,0);turnRate.set(0,0);mouseMotion.set(0,0);toast(autoPilot?'Autopilot engaged: '+target.name+'. F or steering keys to cancel.':'Manual flight control');}
$('start').onclick=()=>{start();captureMouse();};$('mapButton').onclick=openMap;$('closeMap').onclick=closeMap;$('warp').onclick=()=>setTarget(selected);$('weaponUpgrade').onclick=()=>upgrade('weapon');$('shieldUpgrade').onclick=()=>upgrade('shield');$('pauseButton').onclick=pause;$('resume').onclick=()=>{mode==='dead'?start():pause();captureMouse();};$('pauseMap').onclick=openMap;
function captureMouse(){if(mode!=='playing'||document.pointerLockElement)return;try{const request=renderer.domElement.requestPointerLock();if(request&&request.catch)request.catch(()=>toast('Mouse capture unavailable. Arrow keys and screen steering still work.'));}catch{toast('Use arrow keys or move the mouse to steer.');}}
document.addEventListener('pointerlockchange',()=>{steer.set(0,0);turnRate.set(0,0);mouseMotion.set(0,0);if(!document.pointerLockElement&&mode==='playing')pause();});
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(['KeyW','KeyS','KeyA','KeyD','KeyQ','KeyR','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))autoPilot=false;if(e.repeat)return;if(e.code==='KeyM'){if(mode==='map')closeMap();else openMap();}if(e.code==='Escape'){if(mode==='map')closeMap();else pause();}if(e.code==='KeyE')nova();if(e.code==='KeyF')toggleAuto();});window.addEventListener('keyup',e=>keys[e.code]=false);
renderer.domElement.addEventListener('pointermove',e=>{if(mode==='playing'){if(document.pointerLockElement===renderer.domElement){mouseMotion.x+=e.movementX*.0022;mouseMotion.y+=e.movementY*.0022;if(Math.abs(e.movementX)+Math.abs(e.movementY)>2)autoPilot=false;}else steer.set((e.clientX/innerWidth-.5)*2,(e.clientY/innerHeight-.5)*2);}});renderer.domElement.addEventListener('pointerleave',()=>steer.set(0,0));renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===0&&mode==='playing'){firing=true;captureMouse();}});window.addEventListener('pointerup',()=>firing=false);window.addEventListener('blur',()=>{for(const k in keys)keys[k]=false;steer.set(0,0);turnRate.set(0,0);mouseMotion.set(0,0);firing=false;if(mode==='playing')pause();});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);effects.resize();});
const lookMatrix=new THREE.Matrix4(),desiredOrientation=new Q(),turn=new Q(),tmp=new V();
function steerShip(dt){if(autoPilot){const delta=target.pos.clone().sub(ship.position);const navigationPoint=target.pos.clone();const route=delta.clone().normalize();for(const p of planets){if(p===target)continue;const toPlanet=p.pos.clone().sub(ship.position),along=toPlanet.dot(route);if(along<=0||along>Math.min(delta.length(),2200))continue;const perpendicular=toPlanet.clone().addScaledVector(route,-along);const margin=p.radius+180;if(perpendicular.length()<margin){let away=perpendicular.negate();if(away.length()<1)away.copy(up);navigationPoint.copy(p.pos).add(away.normalize().multiplyScalar(margin+180));break;}}lookMatrix.lookAt(ship.position,navigationPoint,up);desiredOrientation.setFromRotationMatrix(lookMatrix);ship.quaternion.slerp(desiredOrientation,1-Math.exp(-dt*2));const distance=delta.length()-target.radius;const alignment=forward.dot(navigationPoint.clone().sub(ship.position).normalize());const desired=distance>500?Math.min(850,(distance-350)*.6):0;speed=THREE.MathUtils.damp(speed,alignment>.9?desired:Math.min(desired,25),2.5,dt);if(distance<510){autoPilot=false;speed=0;toast('Orbit reached. Manual control. Defeat the alien fleet, or fly on.');}}
 else{const response=v=>{const t=Math.max(0,(Math.min(1,Math.abs(v))-.035)/.965);return Math.sign(v)*t*(.65+.35*t);};
 const precision=((firing||keys.Space)&&aimTarget) ? .66 : 1;
 const captured=document.pointerLockElement===renderer.domElement;const fraction=1-Math.exp(-dt*28);const mx=captured?mouseMotion.x*fraction:0,my=captured?mouseMotion.y*fraction:0;mouseMotion.x-=mx;mouseMotion.y-=my;
 const yaw=(keys.ArrowLeft||keys.ArrowRight?((keys.ArrowLeft?1:0)-(keys.ArrowRight?1:0))*1.35:captured?-mx/dt:-response(steer.x)*1.45)*precision;
 const pitch=(keys.ArrowUp||keys.ArrowDown?((keys.ArrowUp?1:0)-(keys.ArrowDown?1:0))*1.2:captured?-my/dt:-response(steer.y)*1.3)*precision;
 turnRate.x=captured&&!keys.ArrowLeft&&!keys.ArrowRight?yaw:THREE.MathUtils.damp(turnRate.x,yaw,yaw===0||yaw*turnRate.x<0?32:16,dt);
 turnRate.y=captured&&!keys.ArrowUp&&!keys.ArrowDown?pitch:THREE.MathUtils.damp(turnRate.y,pitch,pitch===0||pitch*turnRate.y<0?32:16,dt);
 ship.quaternion.multiply(turn.setFromAxisAngle(upAxis,turnRate.x*dt));
 ship.quaternion.multiply(turn.setFromAxisAngle(rightAxis,turnRate.y*dt));const cruise=keys.ShiftLeft||keys.ShiftRight;let desired=cruise?900:keys.KeyW?(enemies.length?78:120):0;if(keys.KeyS)desired=0;speed=THREE.MathUtils.damp(speed,desired,keys.KeyS?4:1.5,dt);}
 ship.quaternion.normalize();forward.copy(forwardAxis).applyQuaternion(ship.quaternion);right.copy(rightAxis).applyQuaternion(ship.quaternion);up.copy(upAxis).applyQuaternion(ship.quaternion);
 if(!autoPilot){ship.position.addScaledVector(right,((keys.KeyD?1:0)-(keys.KeyA?1:0))*dt*55);ship.position.addScaledVector(up,((keys.KeyR?1:0)-(keys.KeyQ?1:0))*dt*55);}
 // Automatic proximity limiter prevents cruise from tunnelling through planets.
 let nearest=null,best=Infinity;for(const p of planets){const distance=ship.position.distanceTo(p.pos)-p.radius;if(distance<best){best=distance;nearest=p;}if(distance<600&&forward.dot(tmp.copy(p.pos).sub(ship.position).normalize())>.3)speed=Math.min(speed,Math.max(15,(distance-25)*1.1));}
 ship.position.addScaledVector(forward,speed*dt);
 for(const p of planets){const delta=tmp.copy(ship.position).sub(p.pos),distance=delta.length();if(distance<p.radius+18){ship.position.copy(p.pos).add(delta.normalize().multiplyScalar(p.radius+19));speed=0;damage(12);toast('Atmosphere boundary · turn away to climb into space');}}
 if(best<650&&nearest!==current)enterOrbit(nearest);else if(current&&ship.position.distanceTo(current.pos)>current.radius+1100){if(enemies.length)getEncounter(current).wave=Math.max(0,getEncounter(current).wave-1);clearObjects(enemies);clearObjects(bullets);current=null;toast('Leaving orbit. Open space ahead.');}
 shipModel.rotation.z=THREE.MathUtils.damp(shipModel.rotation.z,autoPilot?0:turnRate.x*.2,9,dt);}
const segment=new THREE.Line3(),closest=new V();
function update(dt){elapsed+=dt;fireTimer-=dt;invulnerable-=dt;combatIdle+=dt;novaCooldown=Math.max(0,novaCooldown-dt);steerShip(dt);if(mode!=='playing')return;
 const previousTarget=aimTarget;aimTarget=null;let bestDot=.955;for(const e of enemies){const d=e.obj.position.clone().sub(ship.position),dist=d.length(),dot=d.normalize().dot(forward);const score=dot+(e===previousTarget ? .018 : 0);if(dist<850&&dot>.95&&score>bestDot){bestDot=score;aimTarget=e;}}$('reticle').classList.toggle('locked',!!aimTarget);
 if((firing||keys.Space)&&fireTimer<=0){fireTimer=.19-(save.weapon-1)*.011;const dir=aimTarget?aimTarget.obj.position.clone().addScaledVector(aimTarget.velocity,Math.min(1,ship.position.distanceTo(aimTarget.obj.position)/(480+speed))).sub(ship.position).normalize():forward;for(const side of [-1,1])shot(ship.position.clone().addScaledVector(right,side*2.9).addScaledVector(forward,4),dir,false,14+save.weapon*7);}
 if(current&&!getEncounter(current).cleared&&!enemies.length){spawnTimer-=dt;if(spawnTimer<=0)spawnWave();}
 for(const e of enemies){e.t+=dt;e.shot-=dt;const dir=ship.position.clone().sub(e.obj.position),dist=dir.length();dir.normalize();let moveSpeed=e.type==='swarm'?40:e.type==='brute'?16:24;if(e.type==='wisp'){dir.addScaledVector(right,Math.sin(e.t*2)*.7).addScaledVector(up,Math.cos(e.t)*.4).normalize();moveSpeed=45;}if(e.type==='charger'){if(e.t>3){e.t=0;e.charge.copy(dir);}if(e.t<.8&&e.charge.lengthSq()){dir.copy(e.charge);moveSpeed=130;}}
 if(e.type==='shooter'||e.type==='jelly')moveSpeed=dist>170?30:dist<100?-20:0;
 if(e.shot<=0&&(e.type==='shooter'||e.type==='jelly'||e.boss)){e.shot=e.boss?1.3:2.2;shot(e.obj.position.clone(),ship.position.clone().sub(e.obj.position).normalize(),true,9+current.tier);if(e.type==='jelly'||e.boss)for(const sign of [-1,1])shot(e.obj.position.clone(),dir.clone().addScaledVector(right,sign*.17).normalize(),true,8+current.tier);}
 e.velocity.copy(dir).multiplyScalar(moveSpeed);e.obj.position.addScaledVector(e.velocity,dt);const outward=tmp.copy(e.obj.position).sub(current.pos);if(outward.length()<current.radius+15)e.obj.position.copy(current.pos).add(outward.normalize().multiplyScalar(current.radius+16));animateAlien(e,elapsed);e.obj.lookAt(ship.position);if(dist<(e.boss?15:9))damage(e.type==='brute'?22:12);}
 for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.life-=dt;b.previous.copy(b.obj.position);b.obj.position.addScaledVector(b.velocity,dt);segment.set(b.previous,b.obj.position);let hit=false;if(b.enemy){segment.closestPointToPoint(ship.position,true,closest);if(closest.distanceTo(ship.position)<4){damage(b.damage);hit=true;}}
 else for(let j=enemies.length-1;j>=0;j--){const e=enemies[j];segment.closestPointToPoint(e.obj.position,true,closest);if(closest.distanceTo(e.obj.position)<(e.boss?15:e.type==='brute'?7:5.5)){e.hp-=b.damage;hit=true;if(e.hp<=0)defeat(j);break;}}
 if(hit||b.life<=0){disposeObject(b.obj);bullets.splice(i,1);}}
 for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.obj.position.addScaledVector(p.v,dt);if(p.sprite){p.obj.scale.multiplyScalar(1+dt*3);p.obj.material.opacity=Math.max(0,p.life*2);}else p.obj.scale.setScalar(Math.max(.01,p.life));if(p.life<=0){disposeObject(p.obj);particles.splice(i,1);}}
 if(!enemies.length&&combatIdle>8)hp=Math.min(maxHp(),hp+dt*3);}
const projected=new V();
function hud(){ $('hpText').textContent=Math.ceil(hp/maxHp()*100)+'%';$('hpBar').style.width=Math.max(0,hp/maxHp()*100)+'%';$('hpBar').style.background=hp<maxHp()*.3?'#ff947e':'#a6efff';$('credits').textContent='◈ '+save.credits;$('cleared').textContent=String(save.cleared.length).padStart(2,'0');$('upgradeText').textContent=`PLASMA MK ${save.weapon} · SHIELD MK ${save.shield}`;$('nova').textContent=novaCooldown>0?`NOVA RECHARGING / ${Math.ceil(novaCooldown)}s`:'NOVA READY / E';$('speed').textContent=Math.round(speed);$('flightMode').textContent=autoPilot?'AUTOPILOT':speed>160?'CRUISE DRIVE':speed>2?'FREE FLIGHT':'HOLDING POSITION';$('coordinates').textContent=ship.position.toArray().map(v=>Math.round(v)).join(' / ');
 $('sector').textContent=current?current.biome.name.toUpperCase()+' / ORBIT':'KESTREL / DEEP SPACE';$('planetName').textContent=current?current.name:'The open universe';$('mission').textContent=current?`Altitude ${formatDistance(ship.position.distanceTo(current.pos)-current.radius)} · Threat level ${current.tier}`:PLANET_COUNT+' worlds · Fly anywhere · No boundaries';
 const done=current&&getEncounter(current).cleared;$('objective').textContent=current?(done?'Orbit secured ✓':'Defeat the orbital fleet'):'Follow your curiosity';$('wave').textContent=current?(done?'All hostiles defeated':`Fleet ${wave} / ${current.tier>4?3:2} · ${enemies.length} hostiles`):`Destination: ${target.name}`;$('waveBar').style.width=done?'100%':(totalEnemies?kills/totalEnemies*100:0)+'%';$('enemyInfo').textContent=current?(done?'Choose another world on the map, or simply fly.':current.biome.mob+' · Aim near an enemy for weapon lock'):formatDistance(ship.position.distanceTo(target.pos)-target.radius)+' to atmosphere · F for autopilot';
 projected.copy(target.pos).project(camera);const inFront=tmp.copy(target.pos).sub(camera.position).dot(forward)>0;const x=THREE.MathUtils.clamp(projected.x*(inFront?1:-1),-.83,.83),y=THREE.MathUtils.clamp(projected.y*(inFront?1:-1),-.67,.67);$('waypoint').style.left=(x*.5+.5)*innerWidth+'px';$('waypoint').style.top=(-y*.5+.5)*innerHeight+'px';$('waypoint').innerHTML=`${target.name.toUpperCase()}<span>${formatDistance(ship.position.distanceTo(target.pos)-target.radius)}${inFront?'':' · BEHIND YOU'}</span>`;
 $('reticle').querySelector('b').style.transform=`translate(${steer.x*65}px,${steer.y*65}px)`;drawRadar();}
const enemyLabelNodes=new Map();
function drawEnemyLabels(){const live=new Set(enemies);for(const [enemy,node] of enemyLabelNodes)if(!live.has(enemy)){node.remove();enemyLabelNodes.delete(enemy);}for(const e of enemies){let node=enemyLabelNodes.get(e);if(!node){node=document.createElement('div');node.className='enemyLabel';node.innerHTML='<div class="enemyBracket"></div><div class="enemyHealth"><i></i></div><span></span>';$('enemyLabels').appendChild(node);enemyLabelNodes.set(e,node);}const front=e.obj.position.clone().sub(camera.position).dot(forward)>0;const projected=e.obj.position.clone().project(camera);const visible=front&&Math.abs(projected.x)<.96&&Math.abs(projected.y)<.88;node.style.display=visible?'block':'none';if(!visible)continue;node.style.left=(projected.x*.5+.5)*innerWidth+'px';node.style.top=(-projected.y*.5+.5)*innerHeight+'px';node.classList.toggle('active',e===aimTarget);node.querySelector('i').style.width=Math.max(0,e.hp/e.maxHp*100)+'%';node.querySelector('span').textContent=(e.boss?'GUARDIAN':e.type.toUpperCase())+' / '+Math.round(e.obj.position.distanceTo(ship.position))+'m';}$('lockInfo').textContent=aimTarget?'TARGET LOCK / LEAD ASSIST':enemies.length?'ACQUIRE TARGET / HOLD SPACE TO FIRE':'';}
const radar=$('radarCanvas').getContext('2d');function drawRadar(){radar.clearRect(0,0,160,160);radar.strokeStyle='#86c9eb30';radar.fillStyle='#02091777';radar.beginPath();radar.arc(80,80,65,0,Math.PI*2);radar.fill();radar.stroke();radar.beginPath();radar.arc(80,80,33,0,Math.PI*2);radar.moveTo(15,80);radar.lineTo(145,80);radar.moveTo(80,15);radar.lineTo(80,145);radar.stroke();for(const p of planets){const d=tmp.copy(p.pos).sub(ship.position);const x=d.dot(right)/90,y=-d.dot(forward)/90;if(Math.hypot(x,y)<63){radar.fillStyle=p===target?'#c4f9ff':'#678ca8';radar.beginPath();radar.arc(80+x,80+y,p===target?3:2,0,7);radar.fill();}}for(const e of enemies){const d=tmp.copy(e.obj.position).sub(ship.position);const x=d.dot(right)/8,y=-d.dot(forward)/8;if(Math.hypot(x,y)<63){radar.fillStyle='#ff8d77';radar.fillRect(79+x,79+y,3,3);}}radar.fillStyle='#d4f9ff';radar.beginPath();radar.moveTo(80,74);radar.lineTo(76,84);radar.lineTo(84,84);radar.closePath();radar.fill();}
function updateView(dt){const desired=ship.position.clone().addScaledVector(forward,-22).addScaledVector(up,6);camera.position.lerp(desired,1-Math.exp(-dt*14));camera.quaternion.slerp(ship.quaternion,1-Math.exp(-dt*30));camera.fov=THREE.MathUtils.damp(camera.fov,speed>160?80:65,3,dt);camera.updateProjectionMatrix();sky.position.copy(camera.position);stars.position.copy(camera.position);
 for(let i=0;i<dustSeeds.length;i++){const v=dustSeeds[i];v.z+=speed*dt;if(v.z>30)v.z=-800;const a=v.clone().applyQuaternion(ship.quaternion).add(ship.position),b=a.clone().addScaledVector(forward,-Math.max(.3,speed*.04));a.toArray(dustArray,i*6);b.toArray(dustArray,i*6+3);}dustGeo.attributes.position.needsUpdate=true;dust.material.opacity=speed>10?.16+Math.min(.5,speed/1500):.08;
 for(let i=0;i<engines.length;i++){const e=engines[i];if(e.isSprite)e.scale.setScalar(2.5+speed*.007+Math.sin(elapsed*50)*.2);else e.scale.y=.5+speed*.004;}for(const p of planets){p.mesh.rotation.y+=dt*.009;const near=ship.position.distanceTo(p.pos)<6000;p.mesh.geometry=near?planetGeo:distantPlanetGeo;p.atmosphere.geometry=near?planetGeo:distantPlanetGeo;if(p.clouds){p.clouds.rotation.y+=dt*.017;p.clouds.visible=near;}}}
resetFlight();hp=maxHp();let last=performance.now(),hudTimer=0;
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(mode==='playing')update(dt);else if(mode==='welcome'){elapsed+=dt;shipModel.rotation.z=Math.sin(elapsed*.4)*.05;}if(mode==='playing'||mode==='welcome')updateView(dt);hudTimer-=dt;if(hudTimer<=0){hud();hudTimer=.1;}if(noticeTimer>0){noticeTimer-=dt;if(noticeTimer<=0)$('notice').classList.remove('show');}drawEnemyLabels();effects.render(scene,camera);}
requestAnimationFrame(frame);
