'use strict';
const stationRooms=[
 {name:'HANGAR / ENGINEERING',x1:-21,x2:21,z1:-48,z2:34},
 {name:'COMMAND / NAVIGATION',x1:-30,x2:30,z1:46,z2:74},
 {name:'SCIENCE / RESEARCH',x1:-59,x2:-5,z1:87,z2:115},
 {name:'CREW QUARTERS / GALLEY',x1:5,x2:59,z1:87,z2:115},
 {name:'MEDICAL / RECOVERY',x1:-26,x2:26,z1:129,z2:157},
 {name:'CUPOLA / OBSERVATION',x1:-13,x2:13,z1:165,z2:184},
 {name:'PRESSURIZED CONNECTING TUNNEL',x1:-7,x2:7,z1:30,z2:176}
];
let stationCrew=[],activeCrew=null,stationWalls=[];
const crewProfiles=[
 {id:'engineer',name:'Jun Park',role:'Flight engineer',room:'Hangar',x:-13,z:22,color:0xffb85c,skin:0xd4a17b},
 {id:'commander',name:'Commander Vale',role:'Mission commander',room:'Command',x:-16,z:61,color:0x80bdff,skin:0x7e4e38},
 {id:'scientist',name:'Dr. Noor',role:'Xenobiologist',room:'Science',x:-37,z:100,color:0x77e2c0,skin:0xb27b54},
 {id:'crew',name:'Mika Reyes',role:'Communications officer',room:'Crew quarters',x:35,z:99,color:0xcba9ff,skin:0xc68e72},
 {id:'medic',name:'Dr. Imani',role:'Station physician',room:'Medical',x:8,z:143,color:0xf1f5fa,skin:0x674632}
];
function stationWalkable(x,z){return stationRooms.some(r=>x>r.x1+.65&&x<r.x2-.65&&z>r.z1+.65&&z<r.z2-.65)&&!stationWalls.some(w=>Math.abs(x-w.x)<w.w/2+.35&&Math.abs(z-w.z)<w.d/2+.35);}
function constrainStationStep(next,previous){if(stationWalkable(next.x,next.z))return;if(stationWalkable(next.x,previous.z)){next.z=previous.z;return;}if(stationWalkable(previous.x,next.z)){next.x=previous.x;return;}next.copy(previous);}
function stationRoom(){return stationRooms.find(r=>walker.x>=r.x1&&walker.x<=r.x2&&walker.z>=r.z1&&walker.z<=r.z2)?.name||'ARK / CONNECTING TUNNEL';}
function stationPanel(pos,scale,color=0xd1dbe2){const m=detail('box',color,groundRoot,pos,scale);m.material.metalness=.05;m.material.roughness=.85;if(scale[1]>=6&&(scale[0]<1||scale[2]<1))stationWalls.push({mesh:m,x:pos[0],z:pos[2],w:scale[0],d:scale[2]});return m;}
function moduleShell(r){const width=r.x2-r.x1,depth=r.z2-r.z1,cx=(r.x1+r.x2)/2,cz=(r.z1+r.z2)/2;
 stationPanel([cx,-.2,cz],[width,.5,depth],0x8d9da8);stationPanel([cx,6.7,cz],[width,.4,depth],0xbac7d1);
 for(const x of [r.x1,r.x2])stationPanel([x,3.2,cz],[.35,6.5,depth]);
 for(const z of [r.z1,r.z2]){if(r.x1<0&&r.x2>0){for(const side of [-1,1]){const start=side<0?r.x1:7,end=side<0?-7:r.x2;stationPanel([(start+end)/2,3.2,z],[end-start,6.5,.35]);}stationPanel([0,6,z],[14,1,.35]);}else stationPanel([cx,3.2,z],[width,6.5,.35]);}
 // The side modules open into the spine through broad pressure hatches.
 if(r.x2<0||r.x1>0){const x=r.x2<0?r.x2:r.x1;const wall=groundRoot.children.find(o=>o.isMesh&&Math.abs(o.position.x-x)<.01&&Math.abs(o.position.z-cz)<.01&&o.scale.y===6.5);if(wall){stationWalls=stationWalls.filter(w=>w.mesh!==wall);disposeObject(wall);}for(const dz of [-1,1])stationPanel([x,3.2,cz+dz*(depth/4+2)],[.35,6.5,depth/2-4]);stationPanel([x,6,cz],[.35,1,8]);}
 for(let z=r.z1+2;z<r.z2;z+=5){stationPanel([cx,6.35,z],[Math.max(3,width-5),.1,.45],0xeffcff).material.emissive.setHex(0x99cfff);for(const x of [r.x1+1,r.x2-1]){stationPanel([x,3,z],[.3,5.8,.3],0x6d879b);detail('box',0x71d6ff,groundRoot,[x,1,z],[.4,.12,2],1);}}
 sign(r.name,groundRoot,[cx,5.2,r.z1+1.5],Math.min(18,width-2)).rotation.y=Math.PI;sign(r.name,groundRoot,[cx,5.2,r.z2-1.5],Math.min(18,width-2));
}
function consoleDesk(x,z,label){stationPanel([x,.8,z],[5,1.6,2.2],0x536b7d);const screen=detail('box',0x79d9fb,groundRoot,[x,1.95,z-.4],[4,1.2,.13],.7);screen.rotation.x=-.28;sign(label,groundRoot,[x,3,z-.6],5);groundObstacles.push({x,z,r:2.7});}
function buildStationModules(){stationCrew=[];stationWalls=[];
 // A narrow central spine connects the larger modules like an orbital research station.
 for(let z=34;z<178;z+=6){stationPanel([0,-.15,z],[14,.4,6],0x8d9da8);stationPanel([0,6.8,z],[14,.3,6],0xbecbd5);for(const x of [-6.7,6.7]){const inRoom=stationRooms.slice(1,6).some(r=>z>r.z1&&z<r.z2);if(!inRoom)stationPanel([x,3.2,z],[.35,6.4,6]);stationPanel([x,3.2,z],[.45,6.4,.35],0x71879a);detail('box',0x85ddff,groundRoot,[x*.95,1,z],[.15,.12,4],1);}detail('box',0xc5ebff,groundRoot,[0,6.5,z],[6,.08,.3],1);detail('box',0xdeb96b,groundRoot,[0,.12,z],[.18,.04,4],.4);}
 for(const room of stationRooms.slice(1,6))moduleShell(room);
 // Command: flight consoles and a rotating holographic star map.
 for(const x of [-22,22])consoleDesk(x,65,x<0?'GATE TELEMETRY':'FLIGHT CONTROL');const hologram=new THREE.Group();hologram.position.set(14,2,55);groundRoot.add(hologram);detail('cylinder',0x56768b,hologram,[0,-1,0],[4,.7,4]);const orb=detail('sphere',Campaign.universes[save.universe].color,hologram,[0,1,0],[2,2,2],.5);orb.material.setValues({wireframe:true});groundDecor.push(orb);groundObstacles.push({x:14,z:55,r:4});
 // Laboratory racks, specimen tanks and hydroponics.
 for(let i=0;i<5;i++){const x=-52+i*7;stationPanel([x,1,110],[4,2,3],0x687f8d);const tank=detail('cylinder',0x6edcc5,groundRoot,[x,3,110],[1.1,3,1.1],.1);tank.material.setValues({transparent:true,opacity:.25,depthWrite:false});detail('crystal',Campaign.universes[save.universe].color,groundRoot,[x,3,110],[.5,1,.5],.8);groundObstacles.push({x,z:110,r:2.2});}consoleDesk(-48,91,'SAMPLE ANALYSIS');
 // Crew galley: tables, seats, sleep lockers, and a window wall.
 for(const x of [22,44]){stationPanel([x,1.1,109],[7,.25,3],0xb79b78);for(const z of [106,112]){stationPanel([x,.55,z],[6,1,1],0x718dab);groundObstacles.push({x,z,r:2});}groundObstacles.push({x,z:109,r:3.6});}
 for(let x=13;x<57;x+=7){stationPanel([x,2.3,89],[5,4.6,1.2],0x8397a6);detail('box',0x7edfff,groundRoot,[x,3.5,89.7],[2,.3,.05],.5);}sign('MAKE YOURSELF AT HOME',groundRoot,[35,5,113],19);
 // Medical and recovery beds; the traveler wakes here after a crossing.
 for(const x of [-17,17]){stationPanel([x,.65,143],[4,1.2,8],0x718fa3);stationPanel([x,1.32,143],[3.8,.3,7.4],0xe2e9ed);stationPanel([x,1.6,145.5],[3.2,.4,1.5],0xc9d7dd);detail('box',0x6affe0,groundRoot,[x,3,148],[3,1.5,.2],.65);groundObstacles.push({x,z:143,r:3});}consoleDesk(-19,133,'VITAL SIGNS');sign('RECOVERY / YOU ARE SAFE',groundRoot,[0,4.8,155],19);
 // A cupola with a broad view out into space.
 const windowPanel=stationPanel([0,3.6,183.5],[23,5,.08],0x7dbad4);windowPanel.material.setValues({transparent:true,opacity:.1,depthWrite:false});for(const x of [-8,0,8])stationPanel([x,3.6,183.2],[.18,5,.15],0x4e7188);const planet=makeMesh(new THREE.SphereGeometry(22,32,24),Campaign.universes[save.universe].color,groundRoot,new V(0,13,250));const cupolaSky=makeMesh(new THREE.SphereGeometry(65,24,16),0x030817,groundRoot,new V(0,8,230));cupolaSky.material.side=THREE.BackSide;planet.material.emissive.setHex(Campaign.universes[save.universe].color);planet.material.emissiveIntensity=.1;
 sign('HANGAR ← / COMMAND / LAB / CREW / MEDICAL →',groundRoot,[0,5.5,37],13).rotation.y=Math.PI;
 for(const profile of crewProfiles)spawnCrew(profile);
}
function spawnCrew(profile){const root=new THREE.Group();root.position.set(profile.x,.12,profile.z);groundRoot.add(root);detail('box',profile.color,root,[0,1.13,0],[.57,.68,.32]);detail('box',0x294158,root,[0,.73,0],[.52,.22,.32]);for(const x of [-.17,.17]){detail('cylinder',0x334c61,root,[x,.4,0],[.12,.65,.12]);detail('box',0x1b2a38,root,[x,.1,.1],[.23,.18,.4]);}const arms=[];for(const x of [-.4,.4]){const arm=new THREE.Group();arm.position.set(x,1.35,0);root.add(arm);detail('cylinder',profile.color,arm,[0,-.23,0],[.12,.52,.12]);detail('sphere',profile.skin,arm,[0,-.57,0],[.11,.14,.1]);arms.push(arm);}const head=new THREE.Group();head.position.y=1.72;root.add(head);detail('sphere',profile.skin,head,[0,0,0],[.23,.27,.23]);detail('sphere',0x25303a,head,[0,.13,-.035],[.235,.18,.23]);for(const x of [-.08,.08])detail('sphere',0x182635,head,[x,.03,.209],[.027,.023,.015]);detail('box',0xd9f5ff,root,[.14,1.28,.173],[.13,.12,.03],.2);const label=sign(profile.name.toUpperCase(),groundRoot,[profile.x,2.55,profile.z],3.6);stationCrew.push({...profile,root,head,arms,label});groundObstacles.push({x:profile.x,z:profile.z,r:.48});}
function closestCrew(){if(groundKind!=='station')return null;return stationCrew.filter(n=>n.root.position.distanceTo(walker)<3.8).sort((a,b)=>a.root.position.distanceToSquared(walker)-b.root.position.distanceToSquared(walker))[0]||null;}
function crewGreeting(n){const u=Campaign.universes[save.universe];const count=securedWorldCount();return ({engineer:`The Kestrel is fueled and ready. ${24-count} worlds left in ${u.name}. Come back with alloy and we can keep your ship ahead of their fleets.`,commander:`Welcome aboard Ark ${save.universe+1}. We have confirmed ${count} of 24 worlds secured. The guardian is holding this universe's black-hole corridor shut.`,scientist:'These fragments are more than salvage. Every planet has pieces of the old gate network. Bring a relic to the lab and we can recover part of its story.',crew:`I have messages from the other stations. They know you are coming. ${save.universe===0?'Some of them have been waiting for years.':'They saw your last crossing light up the sky.'}`,medic:save.universe?'You were unconscious when the recovery crew brought you in. Your vitals are stable. Take a breath before you head back out.':'Welcome aboard. I keep this crew in one piece. If you need supplies before your expedition, just ask.'})[n.id];}
function talkToCrew(n){if(mode!=='walking'||!n)return;activeCrew=n;mode='dialogue';clearInput();releaseMouse();$('crewName').textContent=n.name;$('crewRole').textContent=n.role+' / '+n.room;$('crewPortrait').textContent=n.name.replace('Dr. ','').split(' ').map(w=>w[0]).join('').slice(0,2);$('crewPortrait').style.borderColor='#'+n.color.toString(16).padStart(6,'0');$('crewLine').textContent=crewGreeting(n);$('crewDialogue').classList.remove('hidden');renderCrewChoices();}
function crewChoice(label,action){const button=document.createElement('button');button.textContent=label;button.onclick=action;$('crewChoices').appendChild(button);}
function renderCrewChoices(){const n=activeCrew;$('crewChoices').replaceChildren();crewChoice('Tell me about this station',()=>{$('crewLine').textContent='The Ark is a modular research station. The central tunnel connects command, the science lab, crew quarters, medical, and the cupola. The hangar is at the far end. Follow the amber line toward decreasing module numbers to reach your ship.';});crewChoice('What happens at the black hole?',()=>{$('crewLine').textContent='The guardian stabilizes a passage through the black hole. Destroy it and the corridor pulls your ship across. You will lose consciousness. A recovery team at the next Ark will bring you to medical. Your equipment and discoveries travel with you.';});
 if(n.id==='commander')crewChoice('Assign my next world',()=>{const next=planets.find(p=>!completed.has(p.id));if(next){target=next;selected=next.id;persist();$('crewLine').textContent=`I have plotted ${next.name}. Board the Kestrel in the hangar, then press F in flight to follow the course.`;}else $('crewLine').textContent='All 24 worlds are secured. Launch, enter a secured orbit, open the map, and summon the guardian.';});
 if(n.id==='engineer')crewChoice('Open the ship workshop',()=>{closeCrew();openMap();});
 if(n.id==='medic')crewChoice('Request expedition supplies',()=>{const key=save.universe+':medical';if(save.crewClaims.includes(key)){$('crewLine').textContent='You already have this station’s supply pack. Your hull is fully repaired whenever you dock.';return;}save.crewClaims.push(key);save.inventory.alloy+=3;persist();$('crewLine').textContent='Three alloy packs for the road. Keep them, or trade them for upgrade credits in the workshop. Come back safely.';});
 if(n.id==='scientist')crewChoice('Submit one relic for research',()=>{const key=save.universe+':research';if(save.crewClaims.includes(key)){$('crewLine').textContent='Your relic is already in analysis. The recovered signal points toward the guardian.';return;}if(save.inventory.relic<1){$('crewLine').textContent='First secure a planet, land with L, and look for the golden relic near its ruin. Bring one back to me.';return;}save.inventory.relic--;save.credits+=180;save.crewClaims.push(key);persist();$('crewLine').textContent='There is a station identifier inside. These gates were built to connect people, not trap them. I have transferred 180 research credits to your account.';});
 if(n.id==='crew')crewChoice('Tell me about the crew',()=>{$('crewLine').textContent='Jun checks every bolt on your ship. Noor reads the artifacts. Vale makes the impossible sound like a plan. And Imani waits at medical after every crossing. We come from different worlds, but this station is home.';});}
function closeCrew(){if(mode!=='dialogue')return;$('crewDialogue').classList.add('hidden');activeCrew=null;mode='walking';clearInput();}
function stationLifeTick(dt){if(!groundActive||groundKind!=='station')return;for(const n of stationCrew){n.root.position.y=.12+Math.sin(elapsed*1.7+n.x)*.015;for(let i=0;i<n.arms.length;i++)n.arms[i].rotation.z=Math.sin(elapsed*1.3+i*2+n.x)*.035;if(n.root.position.distanceTo(walker)<10){const angle=Math.atan2(walker.x-n.x,walker.z-n.z);n.root.rotation.y=THREE.MathUtils.damp(n.root.rotation.y,angle,3,dt);}n.label.visible=n.root.position.distanceTo(walker)<25;n.label.lookAt(camera.position);}}
function stationLifeHud(){const show=groundActive&&groundKind==='station'&&mode==='walking';$('stationDirectory').classList.toggle('hidden',!show);if(!show)return;$('stationZone').textContent=stationRoom();$('stationPeople').textContent=stationCrew.map(n=>`${n.name} / ${n.room} · ${Math.round(n.root.position.distanceTo(walker))} m`).join('\n');const nearby=closestCrew();if(nearby)$('footAction').textContent='E · Talk to '+nearby.name;$('footLocation').textContent=`ARK ${save.universe+1} / ${stationRoom()}`;}
$('crewClose').onclick=closeCrew;
// Solar wings and linked pressure modules make the expanded base readable from orbit.
for(let z=95;z<390;z+=70){const module=makeMesh(new THREE.CylinderGeometry(22,22,62,16),0xb9c8d5,stationExterior,new V(0,0,z));module.rotation.x=Math.PI/2;for(const side of [-1,1]){detail('box',0x65829a,stationExterior,[side*78,0,z],[150,2,3]);for(let panel=0;panel<2;panel++){detail('box',0x173969,stationExterior,[side*120,0,z+panel*25-12],[80,.7,22]);for(let x=86;x<=155;x+=9)detail('box',0x71819f,stationExterior,[side*x,.45,z+panel*25-12],[.3,.15,22]);}}}
