const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader']});try{const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404'))errors.push(m.text());});await page.goto(process.env.STARFARER_URL||'http://127.0.0.1:8765');await page.click('#start');await page.click('#briefingContinue');await page.keyboard.down('w');await page.waitForTimeout(800);await page.keyboard.up('w');assert(await page.evaluate(()=>walker.z<21));await page.evaluate(()=>{walker.copy(parkedShip.position).add(new V(0,1,5));});await page.keyboard.press('e');assert.equal(await page.evaluate(()=>mode),'launch');await page.waitForFunction(()=>!document.pointerLockElement);await page.waitForTimeout(250);await page.evaluate(()=>{for(let i=0;i<100;i++)expeditionTick(.05);});assert.equal(await page.evaluate(()=>mode),'playing');assert.equal(await page.evaluate(()=>groundActive),false);await page.keyboard.press('s');await page.evaluate(()=>{keys.KeyS=true;for(let i=0;i<60;i++)steerShip(1/60);keys.KeyS=false;});assert(await page.evaluate(()=>speed<0));await page.evaluate(()=>{keys.KeyB=true;for(let i=0;i<120;i++)steerShip(1/60);keys.KeyB=false;});assert.equal(await page.evaluate(()=>speed),0);
// The planet cannot be landed on until its entire encounter is won.
await page.evaluate(()=>{const p=planets[0];ship.position.copy(p.pos).add(new V(0,0,p.radius+400));current=p;tryLanding();});assert.equal(await page.evaluate(()=>mode),'playing');assert.match(await page.locator('#notice').textContent(),/blocked/);
// Exercise the real final-wave defeat path rather than assigning the secured flag.
await page.evaluate(()=>{clearObjects(enemies);wave=2;const visual=buildAlien('swarm',current.biome.color,false);scene.add(visual.obj);enemies.push({obj:visual.obj,boss:false});defeat(0);clearObjects(bullets);tryLanding();});assert.equal(await page.evaluate(()=>mode),'landing');await page.evaluate(()=>{for(let i=0;i<65;i++)expeditionTick(.05);});assert.equal(await page.evaluate(()=>groundKind),'surface');assert.equal(await page.evaluate(()=>mode),'walking');await page.waitForTimeout(600);await page.screenshot({path:'/tmp/starfarer-surface.png'});const initial=await page.evaluate(()=>save.credits);await page.evaluate(()=>{walker.copy(groundPickups[0].root.position);groundInteract();});assert(await page.evaluate(()=>save.inventory.alloy===1));assert(await page.evaluate(()=>save.credits)>initial);await page.evaluate(()=>{walker.copy(parkedShip.position).add(new V(0,1,5));groundInteract();for(let i=0;i<100;i++)expeditionTick(.05);});assert.equal(await page.evaluate(()=>mode),'playing');
// Dock at the physical base and verify that the collected pickup stays absent on a repeat landing.
await page.evaluate(()=>{ship.position.set(0,0,-210);current=null;tryLanding();for(let i=0;i<65;i++)expeditionTick(.05);});assert.equal(await page.evaluate(()=>groundKind),'station');await page.evaluate(()=>{surfaceWorld(planets[0]);});assert.equal(await page.evaluate(()=>groundPickups.length),7);
// Unlock the boss only after 24 worlds, then use its defeat path to cross universes.
await page.evaluate(()=>{groundActive=false;mode='playing';current=planets[0];ship.position.copy(current.pos).add(new V(0,0,current.radius+400));for(const p of planets.slice(0,23)){completed.add(p.id);if(!save.cleared.includes(p.id))save.cleared.push(p.id);}summonBoss();});assert.equal(await page.evaluate(()=>finalActive),false);await page.evaluate(()=>{const p=planets[23];completed.add(p.id);save.cleared.push(p.id);mapReturn='playing';summonBoss();});assert.equal(await page.evaluate(()=>mode),'arrival');await page.evaluate(()=>{storyTick(6.1);defeat(enemies.indexOf(finalBoss));storyTick(6.1);});assert.equal(await page.evaluate(()=>save.universe),1);assert.equal(await page.evaluate(()=>groundKind),'station');assert.equal(await page.evaluate(()=>planets.length),24);assert(await page.evaluate(()=>planets.every(p=>p.universe===1)));assert.equal(await page.evaluate(()=>save.inventory.alloy),1);await page.reload();await page.click('#start');assert.equal(await page.evaluate(()=>groundKind),'station');assert.equal(await page.evaluate(()=>save.universe),1);assert.equal(await page.evaluate(()=>save.inventory.alloy),1);
// Finish remaining universe guardians and verify the final ending is reachable.
await page.evaluate(()=>{for(let u=1;u<6;u++){selectUniverse();groundActive=false;mode='playing';mapReturn='playing';current=planets[0];for(const p of planets){completed.add(p.id);if(!save.cleared.includes(p.id))save.cleared.push(p.id);}ship.position.copy(current.pos).add(new V(0,0,current.radius+400));summonBoss();storyTick(6.1);defeat(enemies.indexOf(finalBoss));storyTick(6.1);}});assert.equal(await page.evaluate(()=>mode),'won');assert.equal(await page.evaluate(()=>save.storyComplete),true);assert.equal(await page.evaluate(()=>save.bosses.length),6);assert.equal(await page.evaluate(()=>save.cleared.length),144);assert.deepEqual(errors,[]);console.log('PASS browser journey: opening, walking, boarding, launch, reverse/brake, combat-gated landing, real fleet reward, surface collectibles, docking, pickup persistence, 24-world gate, all six universe transitions, saved campaign, final ending.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
