const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const THREE=require('../vendor/three.min.js');
const source=readFileSync(require.resolve('../space.js'),'utf8');
const elements={};let stored;
const c=vm.createContext({THREE,assert,console,localStorage:{setItem:(_,v)=>stored=v,getItem:()=>stored},$:id=>elements[id]??=( {textContent:'',classList:{add(){}}}),document:{pointerLockElement:null},renderer:{domElement:{}},toast(){}});
vm.runInContext(`const V=THREE.Vector3;const ship=new THREE.Object3D(),camera=new THREE.Object3D(),shipModel=new THREE.Object3D();const forwardAxis=new V(0,0,-1),rightAxis=new V(1,0,0),upAxis=new V(0,1,0),forward=forwardAxis.clone(),right=rightAxis.clone(),up=upAxis.clone(),tmp=new V(),turn=new THREE.Quaternion(),turnRate=new THREE.Vector2(),mouseMotion=new THREE.Vector2(),steer=new THREE.Vector2();let finalActive=false,planets=[],keys={},autoPilot=false,speed=0,aimTarget=null,firing=false,current=null,enemies=[],started=true,mode='playing',hp=83,novaCooldown=7,target={id:2},selected=0;let save={credits:321,weapon:3,shield:2,cleared:[1,4],last:2};function maxHp(){return 130;}function resetFlight(){ship.position.set(0,0,0);ship.quaternion.identity();speed=0;hp=maxHp();} `,c);
vm.runInContext(source.slice(source.indexOf('function steerShip('),source.indexOf('const segment=')),c);
vm.runInContext(`keys={KeyS:true};for(let i=0;i<120;i++)steerShip(1/60);assert(speed < -60);assert(ship.position.z>0);keys={KeyB:true,KeyS:true,KeyW:true,ShiftLeft:true,KeyD:true};autoPilot=true;const x=ship.position.x;for(let i=0;i<120;i++)steerShip(1/60);assert.equal(speed,0);assert.equal(ship.position.x,x);assert.equal(autoPilot,false);keys={KeyW:true};for(let i=0;i<120;i++)steerShip(1/60);assert(speed>100);keys={KeyB:true};for(let i=0;i<120;i++)steerShip(1/60);assert.equal(speed,0);`,c);
vm.runInContext(source.split('\n').find(l=>l.startsWith('function persist()')),c);
vm.runInContext(`ship.position.set(123,456,789);assert(persist());`,c);
assert.equal(JSON.parse(stored).credits,321);
assert.deepEqual(JSON.parse(stored).flight.position,[123,456,789]);
vm.runInContext(`const PLANET_COUNT=96;`,c);
vm.runInContext(source.slice(source.indexOf('let savedFlight=null;'),source.indexOf('function persist()')),c);
vm.runInContext(source.split('\n').find(l=>l.startsWith('function start()')),c);
vm.runInContext(`started=false;planets=Array.from({length:96},(_,id)=>({id}));start();assert.equal(ship.position.x,123);assert.equal(hp,83);assert.equal(target.id,2);assert.equal(novaCooldown,7);assert.equal(speed,0);mode='dead';persist();`,c);
assert.equal(JSON.parse(stored).flight,null);
vm.runInContext(`localStorage.setItem=()=>{throw Error('blocked');};assert.equal(persist(),false);`,c);
assert.match(elements.saveStatus.textContent,/unavailable/);
console.log('PASS: reverse, forward, braking priority, save/reload, death reset, blocked storage');
