const {readFileSync}=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');const THREE=require('../vendor/three.min.js');const source=readFileSync(require.resolve('../space.js'),'utf8');
const nodes={};let writes=0;const c=vm.createContext({THREE,assert,document:{pointerLockElement:null},$:id=>nodes[id]??={textContent:'',style:{},classList:{add(){},remove(){},toggle(){}}},persist(){writes++;},toast(){},captureMouse(){}});
vm.runInContext(`const PLANET_COUNT=96;const V=THREE.Vector3;const scene=new THREE.Scene(),ship=new THREE.Object3D(),camera=new THREE.PerspectiveCamera(),forward=new V(0,0,-1),up=new V(0,1,0);const planets=Array.from({length:96},(_,id)=>({id,pos:new V(0,0,200),radius:20}));const completed=new Set();let current=planets[0],save={storyComplete:false},mode='map',autoPilot=true,speed=90,firing=true,keys={KeyW:true},hp=10,novaCooldown=10,invulnerable=0;const enemies=[],bullets=[];const alienGeometry={ring:new THREE.TorusGeometry()};function getEncounter(p){return {cleared:completed.has(p.id)};}function closeMap(){mode='playing';}function clearObjects(a){for(const e of a)e.obj.removeFromParent();a.length=0;}function maxHp(){return 130;}function buildAlien(){return {obj:new THREE.Object3D(),body:new THREE.Object3D()};}function makeMesh(g,c,parent,pos){const m=new THREE.Mesh(g);m.position.copy(pos);parent.add(m);return m;}function animateAlien(){}function disposeObject(o){o.removeFromParent();}`,c);
vm.runInContext(source.slice(source.indexOf('let finalActive=false'),source.indexOf("$('summonBoss').onclick=")),c);
vm.runInContext(source.split('\n').find(l=>l.startsWith('function defeat(')),c);
vm.runInContext(`summonBoss();assert.equal(finalActive,false);for(let i=0;i<6;i++)completed.add(i);summonBoss();assert.equal(finalActive,false);for(let i=6;i<95;i++)completed.add(i);summonBoss();assert.equal(finalActive,false);storyHud();assert.equal($('summonBoss').disabled,true);completed.add(95);current=null;summonBoss();assert.equal(finalActive,false);current=planets[0];summonBoss();assert.equal(mode,'arrival');assert.equal(enemies.length,1);assert.equal(hp,130);assert.equal(speed,0);assert.equal(keys.KeyW,false);assert.equal(novaCooldown,0);storyTick(3);assert.equal(mode,'arrival');assert(finalBoss.obj.scale.x>0);storyTick(3);assert.equal(mode,'playing');assert.equal(portal,null);finalBoss.hp=1500;storyHud();assert.equal($('bossPhase').textContent,'PHASE II · OVERDRIVE');defeat(0);assert.equal(save.storyComplete,true);assert.equal(mode,'ending');storyTick(6);assert.equal(mode,'won');assert.equal(enemies.length,0);assert.equal(finalBoss,null);assert.equal(finalActive,false);summonBoss();assert.equal(enemies.length,0);`,c);
assert(writes>=2);
// Upgrade migration preserves legacy saves and completion while bounding levels.
let storage=JSON.stringify({engine:4,rapid:99,nova:-4,storyComplete:true});const migration=vm.createContext({localStorage:{getItem:()=>storage}});
vm.runInContext('const PLANET_COUNT=96;let save={cleared:Array.from({length:96},(_,i)=>i)};'+source.slice(source.indexOf('const upgradeTypes='),source.indexOf('let savedFlight=null;')),migration);
assert.equal(vm.runInContext('save.engine',migration),4);assert.equal(vm.runInContext('save.rapid',migration),8);assert.equal(vm.runInContext('save.nova',migration),1);assert.equal(vm.runInContext('save.storyComplete',migration),true);
console.log('PASS: 96-world requirement, safe summoning, arrival animation, boss phase, ending, saved completion, upgrade migration');
